### ISSUE TITLE
mtc time jumps

### ISSUE THREAD

**Issue by Radiokryl** [benkuper/Chataigne#118]
OS: Windows 10
Version 1.9.4

MTC from virtual port is playing unstable (with jitters) in Chataigne.
Source - Reaper MTC 25 or 30 fps,
Result - Lost actions. E.g. MTC 25FPS 1:00:20:00 is always ignored.

**To Reproduce**
1. Run Loop MIDI, start port
2. Run Reaper, add MTC generator, sent it to Loop Midi's port
3. Add midi input in Chataigne
4. Add State Action in Chataigne with time 1:00:20:00
5. Play from Reaper - result is ignoring Action.
Timeline is running unstable in Chataigne.

**Comment by benkuper** [comment]
Is the timeline playing ?
Just tested with MTC Sender tool ( https://www.styletronix.net/Software/MTC/info.aspx ), trigger at 1:20:00 (1 hour and 20 minutes) is working
![mtc](https://user-images.githubusercontent.com/1291595/158153557-988297fd-2430-413e-8466-e5b1852ac6bc.gif)

**Comment by Radiokryl** [comment]
Hello, Benjamin! Thanks for Your answer!
Yes, timeline is playing, but not as smooth as it should.

Here is my setup.
"State" action at 1:00:10
"State 1" action at 1:00:20
"State 2" action at 1:00:30
Results are in videos.
Reaper MTC@25fps - lost of actions and time jumps
Reaper MTC@30fps - lost of actions and time jumps
MTC sender@30fps - works wine with smooth time....

videos are quite big, so I have to upload them to fileshere:
https://dropmefiles.com/4s8yH

Thanks anyway! Best regards!

**Comment by benkuper** [comment]
Well I would say it's on reapers fault then, no ? I could try to have more tolerant jumping, right now it's set to 1/10th of second (and it considers it should jump).
Next beta will be set to 1 second jump limit, so if the lag is less than 1 second, it should still trigger

**Comment by Radiokryl** [comment]
Thanks, Benjamin!
Never seen this behaviour before in Reaper because software I used is a bit more inertial (grandMA2). It needs at least 0.5 seconds to understand that timecode has stopped.
So, Your idea is great!
