### ISSUE TITLE
Streamdeck on Ubuntu 20.04 is not working unless Chataigne runs with admin privilege

### ISSUE THREAD

**Issue by avilleret** [benkuper/Chataigne#119]
Hi !

I'm trying to use Streamdeck in Chataigne under Ubuntu 20.04.
It works if I start Chataigne with sudo but not without. 
So it is a permission issue. 
But I do have a rule under `/etc/udev/rules` to grant access to Streamdeck device for normal user.
This rules seems to work since I can use streamdeck-ui software without sudo. 

Do you know what I am missing ?

**Comment by benkuper** [comment]
Well I'm really not an expert with this kind of things. Basically I understand that any serial device needs admin privilege to run, or maybe some other settings can do the trick.
I'm mainly referring to the Arduino community for these questions as they have the same problem with their IDE. To me this does not seem to be a purely Chataigne problem but a general access from apps.
If something can be done from Chataigne, I'll be happy to integrate it (it's also problematic for the DMX module).

Maybe this would help ? 
https://askubuntu.com/questions/210177/serial-port-terminal-cannot-open-dev-ttys0-permission-denied

It seems that this would help :
`
sudo usermod -a -G dialout $USER
`

**Comment by avilleret** [comment]
well on linux, device access is managed by udev
the command you send just add the current user to the `dialout` group which might fix the issue if the device is assign to that group
changing access permission, owner and group of a device is typically done via udev rules. (usually located in `/etc/udev/rules.d`)
each time a new device is connected those rules are executed

in the case of the streaming deck I added some rules as describe here : https://dev.to/erikaheidi/how-to-set-up-elgatos-stream-deck-on-ubuntu-linux-2110-pdh
and it works since I can access the streamdeck with the `streamdeck-ui` application as a normal user
and what is strange is that it doesn't work from Chataigne unless I started it as root.

Unfortunately I don't have a streamdeck under the hand to run any more test but I suspect something magic with Appimage but can't find any related ressources on it (and unpacking the Appimage and running it from command line doens't work either)
Maybe the magic is on streamdeck-ui side (which for example could run as dialout user...)

**Comment by benkuper** [comment]
well you could reach out to the streamdeck team. I've contacted them in the past but never got an answer, so I'm not spending much time on it (I don't even have one).
If you find a solution, please let me know :)
I would have thought about the AppImage as well, since it recreates a filesystem on its own, but device access... outside my knowledge for sure :

**Comment by benkuper** [comment]
You can also ask on Discord, some people are using linux and may have the answer !
