### ISSUE TITLE
OSCQuery : allow to display OSC address instead of description

### ISSUE THREAD

**Issue by avilleret** [benkuper/Chataigne#120]
When trying to control an amazing software with dynamic OSCQuery namespace, it appears that if 2 nodes have the same description (in the OSCQuery vocabulary) then only one appear on Chataigne.
Since OSC addresses are unique according to OSCQuery specification, it could be nice to be able to select OSCQuery node by address instead of description.

merci 
bisou
:)

**Comment by benkuper** [comment]
Hey Antoine !
What is this amazing software ?? I'm intrigued... :)
b27 now has an option to use address for naming instead of description, please test and report if it's working !

Cheers

**Comment by avilleret** [comment]
awesome !
seems to work fine here
concerning the amazing software, it's mine, so I'm biased ;-)
