### ISSUE TITLE
MC6 midi controller/ Chataigne???

### ISSUE THREAD

**Issue by BenKoa3** [benkuper/Chataigne#121]
**Environment**
 - OS: MacOS 11.5.2
 - 
Hi,

I m using a MC6 midi controller from MorningStar ...
and it s impossible make a link in chataigne!
Making a simple state/action
Chataigne can see the data from MC 6 (PC for example)
but Consequences don't react!!!

any ideas??

Thanx

**Comment by benkuper** [comment]
If it sees the data, then your problem is likely to be in the condition parameters

**Comment by benkuper** [comment]
Or if your parameter doesn't change its value, then you have to use "always notify changes" along with "always trigger"

**Comment by BenKoa3** [comment]
Hi Ben,
Thank you for your answer...but it seems more diffult indeed!
In fact everytime i send data with the MC6 here s what i could read in logs:
(normally it s just a simple PChange)
CustomLoggerUI : Cleared.MC6 : Sysex received, 16 bytes      0      33      36      3      3      8      1      0      0      0      0      0      0      0      18      110MC6 : Sysex received, 29 bytes      0      33      36      3      3      8      0      0      0      0      0      0      0      0      31      2      0      0      0      0      1      1      1      0      0      0      0      0      97MC6 : Program Change : 1, 0MC6 : Sysex received, 16 bytes      0      33      36      3      3      3      48      2      0      0      0      0      0      0      18      86MC6 : Sysex received, 270 bytes      0      33      36      3      3      6      1      0      0      0      0      0      0      2      16      127      0      3      2      0      0      127      1      9      0      1      0      0      0      1      1      2      0      127      1      9      1      1      0      0      0      1      0      2      0      127      1      9      2      0      0      0      0      1      0      2      0      127      1      9      3      0      0      0      0      1      0      2      0      127      1      9      4      0      0      0      0      1      0      2      0      127      1      9      5      0      0      0      0      1      0      2      0      127      1      9      6      0      0      0      0      1      0      2      0      127      1      9      7      0      0      0      0      1      0      2      0      127      1      9      8      0      0      0      0      1      0      2      0      127      1      9      9      0      0      0      0      1      0      2      0      127      1      9      10      0      0      0      0      1      0      2      0      127      1      9      11      0      0      0      0      1      0      2      0      127      1      9      12      0      0      0      0      1      0      2      0      127      1      9      13      0      0      0      0      1      0      2      0      127      1      9      14      0      0      0      0      1      0      2      0      127      1      9      15      0      0      0      0      1      0      2      0      127      2      8      109      105      115      101      32      32      32      32      127      3      8      83      72      104      104      104      104      46      46      127      4      24      77      105      115      101      32      78      111      105      114      32      83      84      79      80      32      32      32      32      32      32      32      32      32      32      127      5      4      0      0      0      0      26MC6 : Sysex received, 243 bytes      0      33      36      3      3      6      2      0      0      0      0      0      0      1      117      127      0      1      2      127      1      1      0      127      2      9      0      0      0      0      0      1      0      0      0      127      2      9      1      0      0      0      0      1      0      0      0      127      2      9      2      0      0      0      0      1      0      0      0      127      2      9      3      0      0      0      0      1      0      0      0      127      2      9      4      0      0      0      0      1      0      0      0      127      2      9      5      0      0      0      0      1      0      0      0      127      2      9      6      0      0      0      0      1      0      0      0      127      2      9      7      0      0      0      0      1      0      0      0      127      2      9      8      0      0      0      0      1      0      0      0      127      2      9      9      0      0      0      0      1      0      0      0      127      2      9      10      0      0      0      0      1      0      0      0      127      2      9      11      0      0      0      0      1      0      0      0      127      2      9      12      0      0      0      0      1      0      0      0      127      2      9      13      0      0      0      0      1      0      0      0      127      2      9      14      0      0      0      0      1      0      0      0      127      2      9      15      0      0      0      0      1      0      0      0      127      3      24      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      32      98
????? Quite strange, isnt it?







    Le lundi 18 avril 2022, 09:39:54 UTC+2, Ben Kuper ***@***.***> a écrit :  
 
 


Or if your parameter doesn't change its value, then you have to use "always notify changes" along with "always trigger"

**Comment by benkuper** [comment]
There are some program change messages in there, but there are also sysex messages.
I encourage you to go to the Discord server and ask you question there, more users will be able to answer.

**Comment by BenKoa3** [comment]
Thank you for your answer…it seems that Chataigne have a real clear vision of what data my controller really send!!!Finally I found the key…my soft needed just un midi message for note off!Everything works great!
Thanks again  


Envoyé depuis Yahoo Mail pour iPhone


Le samedi, avril 30, 2022, 10:23 AM, Ben Kuper ***@***.***> a écrit :




There are some program change messages in there, but there are also sysex messages.
I encourage you to go to the Discord server and ask you question there, more users will be able to answer.
