### ISSUE TITLE
add grandMA3-Chataigne-Module to Community Module Manager

### ISSUE THREAD

**Issue by yastefan** [benkuper/Chataigne#122]
I would like to share my grandMA3 module with the community and would be happy if it is added to the "Community Module Manager". It could be quite useful for some people and if there are further requests for it I would also like to invest some time. 

I haven't gone all the way through the Chataigne repository yet, so it's a feature request and not a pull request. I hope this is ok

https://github.com/yastefan/grandMA3-Chataigne-Module

**Comment by benkuper** [comment]
Thak you for your contribution !
It's added to the list
![image](https://user-images.githubusercontent.com/1291595/168542743-93e50c36-90df-4836-9372-c20bbe036e32.png)
