### ISSUE TITLE
PosiStageNet support

### ISSUE THREAD

**Issue by Kwimbee** [benkuper/Chataigne#124]
**Is your feature request related to a problem? Please describe.**
At the moment, it is not possible to use PosiStageNet with Chataigne, and also not possible to implement it using custom modules, as it is a protocol that uses Multicast.

**Describe the solution you'd like**
Ideally, a core module could be developped, or some changes to the core UDP module could be done to allow subscribing to multicast streams allowing the developpement of a custom module.

**Describe alternatives you've considered**
At the moment, only alternative I could see is the use of Chamsys, a lighting control console/software that is able to both receive PosiStageNet and possibly output OSC or a similar protocol. This would allow PosiStageNet to be converted in a protocol that Chataigne can understand, but it is not ideal as it requires specific skills and adds another software in the loop.

**Additional context**
Initially developed as a means for [VYV](https://www.vyv.ca/)‘s [Photon](https://www.vyv.ca/products/photon/) Media Server to internally communicate the position of freely-moving projection surfaces, PosiStageNet became an open standard through a close collaboration between [VYV](http://vyv.ca/) and [MA Lighting](https://www.malighting.com/), makers of the world-reknowned [GrandMA2](https://www.malighting.com/grandma2/) lighting console.
I can help during troubleshooting or debugging on real hardware, as I have Robe RoboSpots at my disposal, and those can output PosiStageNet

**Comment by benkuper** [comment]
There may be a way to add multicast mode to the UDP module. I don't think creating a separate multicast udp module is a good idea, but letting users choose whether it's unicast/broadcast or multicast can be interesting indeed.
I'll check that

**Comment by Kwimbee** [comment]
yup, might be a good idea.

Another possibility would be to include PosiStageNet as a core module, as there is a C++ library already written for it, maybe easier to implement than creating a custom module based on UDP multicast
