### ISSUE TITLE
OSC module help refers to "OSC Command Model Panel"

### ISSUE THREAD

**Issue by gmatters** [benkuper/Chataigne#125]
In http://benjamin.kuperberg.fr/chataigne/forum/d/84-multiple-custom-osc-commands the command model is deprecated. Probably the help should refer to Command Templates?

**Comment by benkuper** [comment]
I don't see where the term "Command Model" is used now. The official documentation is only referring to Command Templates, and the software doesn't mention Command Model anywhere.

Also, the forum has been closed for few months already now.

**Comment by benkuper** [comment]
This is changed, thank you
