### ISSUE TITLE
State Machine -> Mapping -> Filter -> Inverse does not work

### ISSUE THREAD

**Issue by gmatters** [benkuper/Chataigne#126]
**Environment**
 - OS: MacOS 12.1
 - Version 1.9.6

**Describe the bug**

**To Reproduce**
MIDI module CC into state machine mapping with filter remap to [0,1] outputs to a custom variable
different state machine with a mapping whose input value is the custom variable and filter inverse
output is still in range [0,1] whether inverse is enabled or disabled

however, I can add a remap to [1, 0] and that works

**Expected behavior**
filter inverse should map [0,1] to [1,0]

**Additional context**

**Comment by benkuper** [comment]
Hello,
The remap may force a 0-1 range when no range is defined in the input, which the inverse may not. It could be added but right behaviour is to specify as much as possible parameter's ranges when they're known.
In custom variables, right click on the parameter : 
![image](https://user-images.githubusercontent.com/1291595/168543335-ef1feece-1c22-49c7-b10d-5520741887e5.png)
