### ISSUE TITLE
Custom variable right-click menu is hard to discover

### ISSUE THREAD

**Issue by gmatters** [benkuper/Chataigne#127]
I had tried right-clicking on many different parts of the Chataigne interface, but never found a menu and decided that right-click context menu is just not part of the UI.

However the right-click menu on Custom Variable contains many useful options which I could not discover.

Suggestions:

- tooltip could mention [right click to configure]
- help panel should mention right click, and perhaps help for the things in the right-click menu
- add it to the docs ("Example 2 : Particle system presets" seems like right-click was used to set the range of Size and Speed, but right-click is never discussed or shown)
- perhaps instead of right-click it should be a dot popup menu like state machine MappingOutput, especially since right-click is not widely used elsewhere in the interface

**Comment by benkuper** [comment]
Right click is used a lot, you're right that documentation could help find it more easily (and you're welcome to write some if you want, just ping me on discord and I'll give you access to the doc admin).
I added a paragraph in the ultimate cheat sheet : https://bkuperberg.gitbook.io/chataigne-docs/the-ultimate-cheat-sheet
Also, I think all of the video tutorials show the use of right click for many parts of the software.
