### ISSUE TITLE
Identical mapping outputs behave differently

### ISSUE THREAD

**Issue by gmatters** [benkuper/Chataigne#130]
**Environment**
 - OS: MacOS 12.1
 - Version 1.9.6

**Describe the bug**
Two identical mapping outputs have different behaviour; the first one gets full range of values, the second toggles between min and max.

**To Reproduce**
Trying to extract RGB compenents from a logical value. I set up a mapping with color as input, HSV adjust so I have a fader to quickly change the color for testing, and an output from input's R to a MIDI cc with the "scale to 127" box checked. It works. Duplicate that output, and the CC value in the copy acts as if it is fed by a bool, jumping between 0 and 127.

If I switch the order of the outputs, whatever one is at the top gets the full range and the one below acts like a bool

**Expected behavior**
Identical outputs should behave identically

**Additional context**
<img width="674" alt="Screen Shot 2022-05-28 at 10 15 41 PM" src="https://user-images.githubusercontent.com/188479/170849258-3e14ebd4-afdb-42a7-8834-9a8d7ba65fd8.png">

github won't let me attach the .noisette?

**Comment by benkuper** [comment]
Yes, there is a problem with the MIDI Output that changes the actual value and it's propagating to the next outputs.
