### ISSUE TITLE
Sur 1.9.7 pas possible d'upgrader les sessions anterieures

### ISSUE THREAD

**Issue by Ezrabox** [benkuper/Chataigne#134]
Mac OS 11.2.3
Chataigne 1.9.7 Stable

Bonjour, Chataigne 1.9.7 ne veut pas upgrader mes sessions précedentes, j'ai essayé des sessions de différents projets sur Mac, RaspBerry et Windows, sur Rasp elle ne veut pas non plus faire "Load Directly"

J'ai trouvé une solution en faisant "load directly" sur mac puis "sauver sous" puis en ouvrant la session sur mac ou rasp ça fonctionne

**Comment by benkuper** [comment]
Que se passe-t-il en faisant "update" ?

**Comment by benkuper** [comment]
Can you join the file ? rename it *.txt if the *.noisette is not possible

**Comment by Ezrabox** [comment]
[Uploading 2072NO copie.txt…]()
[QUIALS(2) copie.txt](https://github.com/benkuper/Chataigne/files/9148461/QUIALS.2.copie.txt)

**Comment by benkuper** [comment]
Peux tu ressayer maintenant ?

**Comment by Ezrabox** [comment]
Ça marche sous mac en tout cas! Merci :)
