### ISSUE TITLE
Adding support for SLIP OSC in Serial module

### ISSUE THREAD

**Issue by thomasfredericks** [benkuper/Chataigne#139]
SLIP OSC is a protocol that is used by a few libraries : 
- https://github.com/colinbdclark/osc.js
- https://github.com/thomasfredericks/MicroOsc (mine)
- https://github.com/CNMAT/OSC

Could this protocol be implemented? It would greatly facilitate mapping of OSC parameters over Serial!

I can help with the implementation.

**Comment by benkuper** [comment]
Right now, OSC is part of JUCE so it would be a bit complex to put it out to support serial. Theoretically it would totally be possible, but require some time to avoid duplicating code between the OSC module and the Streaming module, so basically doing it properly.
How big would you estimate the use of that over simpler, more "standard" protocols such as simple line "label value", JSON or COBS ?
I actually used to use this and in the end did not find that so nice to use for serial. But it was a long time ago so maybe it would be better now.

You could try though to implement it as a script. I think everything is there to parse and encode messages, and if you need to add anything on that part I'll be happy to help !

**Comment by thomasfredericks** [comment]
Thanks for the answer. 
I understand the limitations imposed by JUCE and the rationale behind not wanting to duplicate the OSC parsing code. 

About the other protocols, they (COBS, JSON, FUDI, etc), allow too much customization in the way of organizing data, and therefore rely on custom user specific architectures. OSC enforces a set structure and is therefore more universal. It also provides (simple) error checking which is very important on streams!

Thank you for looking into this!

**Comment by benkuper** [comment]
No need to close it though :)
It may just come some time, I didn't want to make you feel that this is not a welcome idea

**Comment by je71175** [comment]
have a look at Chataigne https://benjamin.kuperberg.fr/chataigne/en - its a pretty flexible logic and translation app, which supports OSC and serial.  Maybe you can use this to achive OSC-> Serial mappings needed

**Comment by jgastonraoul** [comment]
+1 on this one !

I find it easier on Arduino to use OSC to send/receive data and would love to be able to receive/send it directly in Chataigne. For now, I need to put a Max patch in between to transform  USB SLIP Serial in UDP...
