### ISSUE TITLE
MatildaGS

### ISSUE THREAD

**Issue by vjblind** [benkuper/Chataigne#14]
The procedure entry point MapViewOffileFromApp couldnot be located in the dynamic link library Kernel32.dll

**Comment by benkuper** [comment]
Please be more specific :
 - What system do you use ?
 - Which version of Chataigne ?
 - Any other relevant information to help diagnose ?

**Comment by benkuper** [comment]
I'm not sure but you may solve this problem by installing the VC2017 Redistributables :
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e653a57a-bc32-4134-87bf-df33058f0531/download-microsoft-visual-c-2017-redistributable?forum=vssetup

**Comment by benkuper** [comment]
With other feedbacks, it seem that you are on Windows 7, right ?
There is a compatibility problem with Win7 with the framework i use, i'll check if i can work around that.
