### ISSUE TITLE
Appimage broken in Ubuntu 22.04

### ISSUE THREAD

**Issue by tatrapikao** [benkuper/Chataigne#140]
There is no libssl.so.1.1 in Ubuntu 22.04 so the Appimage is broken in the current Ubuntu LTS.

**Comment by benkuper** [comment]
Damn.

**Comment by benkuper** [comment]
Could you test the bleeding edge from the website ? I added the libssl dependencies to the AppImage. Couldn't test with a real 22.04 yet so maybe there are 2nd degree deps that I don't know about..

**Comment by benkuper** [comment]
So it seems more complex than just copying the libs.. the whole openssl dependency has changed.

**Comment by benkuper** [comment]
Those lines seem to fix the dependency problem on 22.04 :

```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
```

But now it complains about X11 not being used anymore. Projucer is still working on 22.04 so JUCE is compatible, it may need a separate compilation for 22.04+ though

**Comment by tatrapikao** [comment]
Nice to hear - i know there are workarounds but would be nice to have it working out of the box again.  Thx & keep up the great work!

**Comment by benkuper** [comment]
I ended up removing the welcome screen and adding libssl.so.1.1 in beta 11, please confirm that it works when it's released
