### ISSUE TITLE
The same value is added multiple times after restart

### ISSUE THREAD

**Issue by TPhoenix124** [benkuper/Chataigne#141]
**Environment**
 - OS: Windows 10
 - Version 1.9.7

**Describe the bug**
I added OSC values using Auto Add. This worked fine and I was able to use it in state machine.
After restart, this value doesn't respond any more, but I can see the incoming value in the logging window.
If you keep Auto Add activated, the same value is added over and over again.
I tried to send OSC messages from QLab and Digico SD7Q.

https://user-images.githubusercontent.com/115737415/195682892-e75a086f-1674-4aaf-8f26-a0ba801d5e17.mov

https://user-images.githubusercontent.com/115737415/195682953-aff5d2c9-3fe1-48da-85fc-2e15395309b7.mov

**Comment by benkuper** [comment]
Thanks for reporting, the fix will be included in b11

**Comment by TPhoenix124** [comment]
Thanks for the quick reply. Do you already know when b11 will be released?

**Comment by benkuper** [comment]
Tonight if other fixes are going through :)

**Comment by TPhoenix124** [comment]
Hey,
I just checked it. 
It works, but only if Auto Add is activated. Is this on purpose?

**Comment by benkuper** [comment]
No it's an error :) I'll check it
