### ISSUE TITLE
Unable to open a file created in version 1.9.7

### ISSUE THREAD

**Issue by TPhoenix124** [benkuper/Chataigne#142]
**Environment**
 - OS: Windows 10
 - Version 1.9.8b11

**Describe the bug**
Unable to open a file created in version 1.9.7
Software is not responding.

**Comment by benkuper** [comment]
Please attach the file

**Comment by benkuper** [comment]
You may get better help on the Discord server, the issues are more oriented towards coding questions

**Comment by TPhoenix124** [comment]
[Chataigne-Cabaret.zip](https://github.com/benkuper/Chataigne/files/9783525/Chataigne-Cabaret.zip)

**Comment by TPhoenix124** [comment]
Thanks. I will also try to get some help on Discord.
I just wrote here, because it's a fresh beta release

**Comment by benkuper** [comment]
It's a good one ! I'm on it, will be fixed soon

**Comment by TPhoenix124** [comment]
Wow.
Your reply time is amazing.
Just startet working with the software and already loving it...

**Comment by benkuper** [comment]
I happen to be working on my computer these days.. :)
Found it, fixed it, b12 is cookin'

**Comment by benkuper** [comment]
Done
