### ISSUE TITLE
native silicon

### ISSUE THREAD

**Issue by postprivee** [benkuper/Chataigne#151]
any chance for a native silicon version?

**Comment by benkuper** [comment]
If JUCE is supporting yes, it would be possible yes, but a lot of dependant libraries would have to be recompiled, and that takes a lot of time (which I don't have right now, and not working on mac so even harder).
It will eventually come, but no ETA.
Anyone reading this, you're welcome to PR and provide recompiled libraries :)

What is the drive to get native silicon ? Do you see limitations right now ?

**Comment by postprivee** [comment]
we decided not to install rosetta on studio. so, we'll have to wait (:

**Comment by benkuper** [comment]
Can I ask why ? I don't know so much about it but i'm curious :)

**Comment by benkuper** [comment]
Could you test the latest 1.9.14b4 ? Not sure but I tried something..

**Comment by postprivee** [comment]
@benkuper 1.9.14b4 also requires rosetta. but thank you so much for your time+effort!

**Comment by benkuper** [comment]
Hey ! 
Native silicon has landed :)
You should be able to test the latest beta on silicon, or at least the bleeding edge ! Not sure what's advertised on the website

**Comment by postprivee** [comment]
@benkuper great news! 1.9.14b12 + bleedingedge both native silicon now
