### ISSUE TITLE
When MTC input scrubs, sequence plays

### ISSUE THREAD

**Issue by sebescudie** [benkuper/Chataigne#167]
**Environment**
 - OS: Windows 10
 - Version: 1.9.13

**Describe the bug**
When a sequence is clocked by an external MTC source, scrubbing on this MTC source starts the sequence playback, even though the MTC source is paused.

**To Reproduce**
1. Create a MIDI module, set its input to a [virtual MIDI device](https://www.tobias-erichsen.de/software/loopmidi.html)
2. Open [MTC Sender](https://www.styletronix.net/Software/MTC/info.aspx), set its _MIDI Out_ parameter to the virtual MIDI device
3. In Châtaigne, create a new Sequence, enable _Sync Devices_ and set the input to the virtual MIDI device
4. In MTC Sender, start the playback (Start button) : the sequence playback start
5. In MTC Sender, stop the playback (Pause button) : the sequence playback stops
6. In MTC Sender, move the Time Slider to "scrub" through time : Châtaigne will move the playhead _and_ start the playback. MTC Sender is still paused

**Expected behavior**
When scrubbing on an external MTC source and that source is paused, I would expect Châtaigne to just move the playhead without starting the playback

**Additional context**
Been monitoring MIDI traffic with an external tool ([Protokol](https://hexler.net/protokol)). When scrubbing, MTC Sender sends a SysEx message. It looks like Châtaigne "interprets" this SysEx message as a play order. Tried a bunch of other things :
- Clocking Châtaigne with another Châtaigne instance over the network using [RTP MIDI](https://www.tobias-erichsen.de/software/rtpmidi.html) : same behavior. Scrubbing the Châtaigne timeline starts the playback on the "secondary" Châtaigne instance
- Clocking another tool (Ventuz) using MTC : when scrubbing, it simply moves the playhead without actually starting the playback, which is the behavior I would expect on Châtaigne.

Let me know if I can provide additional details. Thanks!

**Comment by benkuper** [comment]
Can you try the latest bleeding edge ?

**Comment by sebescudie** [comment]
Working just fine now, thanks for the prompt fix. Closing!
