### ISSUE TITLE
State machine size don't get saved

### ISSUE THREAD

**Issue by Lyptik** [benkuper/Chataigne#17]
Chataigne 1.2.13

State machine (visual) size don't get saved when saving then opening a project

**Comment by benkuper** [comment]
This is actually more of a OrganicUI issue since it's not related to Chataigne-specific code but on the ShapeShifterPanel framework included in OrganicUI : https://github.com/benkuper/juce_organicui/issues

Latest commit on OrganicUI fixes the problem, should be fixed in the next version.
