### ISSUE TITLE
Websocket working according to spec?

### ISSUE THREAD

**Issue by bombarie** [benkuper/Chataigne#178]
Hi, I'm just starting to explore the wonderful world of Chataigne. I'm super enthusiastisc about the potential of this tool! I was testing to see how the websockets work and I wonder if my observation is true that the Websocket Server doesn't seem to be able to (validly?) send messages to its clients. 

My observations:

- Chataigne Websocket Server and Websocket Client modules: 
  - client -> server: yes
  - server -> client: no
- Chataigne Websocket Server module and a websocket client in Processing:
  - client -> server: yes
  - server -> client: no
- Chataigne Websocket Server module and a websocket client in web frontend:
  - client -> server: yes
  - server -> client: no
- Processing websocket server and Chataigne Websocket Client:
  - client -> server: yes
  - server -> client: yes
- Processing websocket server and web frontend client:
  - client -> server: yes
  - server -> client: yes

Is there some setting that I'm missing? Configuration of the Preferences? 

This is my Websocket Server config in Chataigne: 
![Websocket Server](https://i.imgur.com/B35BN1I.png)

**Comment by benkuper** [comment]
Good catch, could reproduce and fixed for 1.916b1 (which should be out in the next hour).
Thank you !
