### ISSUE TITLE
[Bug] sequence when opening file don't get really triggered

### ISSUE THREAD

**Issue by Lyptik** [benkuper/Chataigne#18]
When opening a .noisette file which contains an "play at load" Sequence the sequence get triggered correctly but not its content.

Tested with having triggers launching some application with the OS Module.

When launching the .noisette file, the sequence plays but the trigger starting the app don't work.
When clicking on Play on the sequence, it works.

**Comment by benkuper** [comment]
Can't reproduce, can you join the file ?
Testing with an OSC Module and a simple sequence with 3 triggers, when loading, everything works.
