### ISSUE TITLE
Sequence audio envelope automation volume issue

### ISSUE THREAD

**Issue by esairri** [benkuper/Chataigne#180]
**Environment**
 - OS: WIN 10 & 11
 - Chataigne: 1.9.15

**Describe the bug**
When addding envelope automation to an audio file, the volume goes through the roof to astronomical numbers. When the volume is so high, no sound can be heard (which is a good prevention). It is practically impossible to set the volume to a normal level, e.g. between 0.5-1.5 with mouse.

**To Reproduce**
1. Create a sequence
2. Add an audio file
3. Right click the audio wave form in the timeline view and select Edit envelope automation
4. In the timeline view or Inspector adjust the volume by pulling a dot with the mouse
5. You will note that the volume immediately goes to astronomical heights
![Chataigne Volume Issue](https://github.com/benkuper/Chataigne/assets/123733270/a0205f8b-f5f3-4e24-a63e-eb3952239418)

**Expected behavior**
I believe it would make sense if the upper end of the envelope would be limited to max 2 at least in the graphical view.

**Additional context**
Ben, thank you for Chataigne, I am absolutely loving it!

**Comment by benkuper** [comment]
Hello and thank you,
Please ask this kind of questions on Discord, the github issues are for code related matter
