### ISSUE TITLE
The Chataigne Forum is down

### ISSUE THREAD

**Issue by hepiyellow** [benkuper/Chataigne#181]
http://benjamin.kuperberg.fr/chataigne/forum

**Comment by benkuper** [comment]
Yes, the forum has been replaced by the Discord server for a while now. There is no official link to it anymore

**Comment by hepiyellow** [comment]
So how do I find the discord server?

**Comment by djyersson** [comment]
good afternoon to the entire community, please, I have not been able to configure using pan and util parameters in grandma3, what are the values ​​that I should set for the akai apc40

**Comment by benkuper** [comment]
What makes you think you're posting this at the right place... ?
