### ISSUE TITLE
MacOS Shutdown command : force doesn't work

### ISSUE THREAD

**Issue by DonGuig** [benkuper/Chataigne#186]
**Is your feature request related to a problem? Please describe.**
On Mac OS, the "force" option of the shutdown command (OS module) doesn't do anything. By looking at the source code, this "force" option only works on windows.

**Describe the solution you'd like**
On MacOS, applescript seems to be used to trigger shutdown. There is a shell command : "shutdown -h now" that forces shutdown without asking for applications to save their documents. This is the behaviour that I would expect from the "force" option. Thing is, it requires sudo : "sudo shutdown -h now". So it doesn't work as such when using the "Launch Command" command.

**Describe alternatives you've considered**
Is there a way to have Chataigne use the "sudo shutdown -h now" when doing shutdown with force option, without requiring for the user to input its password at the time of exec ?

**Comment by benkuper** [comment]
Did you try launching chataigne as sudo, and from there launching the command with sudo ?

**Comment by DonGuig** [comment]
Yes, it works, but it's a bit of a hack, and still requires to input admnistrator password when you launch Chataigne with sudo.

**Comment by benkuper** [comment]
It would be a concerning security breach if Chataigne could launch sudo commands without being sudo itself. Anybody could do a lot of harm..

**Comment by DonGuig** [comment]
Good point...
