### ISSUE TITLE
ping status not working on windows

### ISSUE THREAD

**Issue by circuitb** [benkuper/Chataigne#187]
- Windows 10 22H2 (tested 2 machines)
 - Version  1.9.8 to last

ping status not working
ip 127.0.0.1 
log:
127.0.0.1 is dead 

the strange part is : it was working 6 month ago (version 1.9.8)
perhaps  some windows update / defender stuff?

**Comment by benkuper** [comment]
what's happening when pinging directly from terminal ?

**Comment by circuitb** [comment]
everything is fine from cmd and other ping softwares
Envoi d’une requête 'Ping'  127.0.0.1 avec 32 octets de données :
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128

Statistiques Ping pour 127.0.0.1:
    Paquets : envoyés = 4, reçus = 4, perdus = 0 (perte 0%),
Durée approximative des boucles en millisecondes :
    Minimum = 0ms, Maximum = 0ms, Moyenne = 0ms

![image](https://github.com/benkuper/Chataigne/assets/1019218/9b2348f2-6010-4ffd-b497-e8518601037a)

**Comment by benkuper** [comment]
ah yes, the way it's done now only works with an english OS... it's parsing the output. If you manage to have your terminal output in english, it should work

**Comment by niklasberlin** [comment]
hope this can be improved in a future version, just spend like two hours debugging why ping was not working on my german windows. Wireshark was like: yep ping messages are send and proper responses were received but chataigne did not recognize this.
maybe there is a better way to check for a successful ping than checking if "Received = 1" is included in the result or we could check for result in multiple languages like english, german, french, ... to at least reduce the number of cases where the current approach does not not work.

in German the check would be:
`bool success = result.contains("Empfangen = 1");`

**Comment by benkuper** [comment]
There must be a better way for sure. didn't get proper time to do that

**Comment by benkuper** [comment]
That may be a good solution : https://github.com/sryze/ping

**Comment by benkuper** [comment]
I improved the current system, it should be more robust to different languages and replies from the ping command on windows, please check with the coming bleeding edge before i roll out the next beta

**Comment by niklasberlin** [comment]
tested with latest bleeding edge build and it looks like ping is now working as expected on my german windows 10 pro version 22H2
