### ISSUE TITLE
script.log() not showing up

### ISSUE THREAD

**Issue by hepiyellow** [benkuper/Chataigne#189]
Hi,

I have a module that uses `script.log()`, but I don't see my logs in the Logger window.
I made sure that changes I make to my module are reflected (the behavior changes),
but the logs don't appear.

Is there some configuration I need to do in Chataigne in order to see these logs?

Thanks

**Comment by benkuper** [comment]
Maybe this ?

![image](https://github.com/benkuper/Chataigne/assets/1291595/8b94a08a-38e1-4cbe-a6c0-a49487b6b65d)

**Comment by benkuper** [comment]
I could yes, I 'll check when I have time
