### ISSUE TITLE
Is OSCQuery supporting custom Websocket configurations?

### ISSUE THREAD

**Issue by joreg** [benkuper/Chataigne#194]
as of https://github.com/Vidvox/OSCQueryProposal#required-attributes the hostinfo can include WS_IP and WS_PORT. my OSCQuery server fills those in but i don't seem to get a connection from Chataigns websocket. just want to understand if this should work or is not supported.

**Comment by benkuper** [comment]
what is your oscquery server ?

**Comment by benkuper** [comment]
mmh youre right, right now Chataigne doesn't care about WS_IP and WS_PORT, but that could totally be added quite simply. I'll check that when I get time

**Comment by benkuper** [comment]
please test the coming bleeding edge to see if the new ws port is working

**Comment by joreg** [comment]
great, how do i know when a new bleeding edge version is available?

**Comment by benkuper** [comment]
In the actions section of the repo

**Comment by benkuper** [comment]
can you post a screenshot of the configuration ?
and can you try just connecting with a websocket client module and see if it works ?

**Comment by joreg** [comment]
connection established. thanks!
