### ISSUE TITLE
OSCQuery Zeroconf issue

### ISSUE THREAD

**Issue by joreg** [benkuper/Chataigne#195]
i have a custom OSCQueryServer that advertises itself via Zeroconf as per the OSCQuery specs. i can see it in a [zeroconf browser](https://hobbyistsoftware.com/bonjourbrowser) and also the "official" [OSCQuery browser](https://docs.vidvox.net/freebies_oscquery_browser.html) but in Chataigne "Auto detect" says "no-service found".

and also the other way round: when enabling "OSC Remote Control" in the Chataigne preferences, the above browsers don't see the service though in the log it says "Zeroconf service created". connecting manually to the port then works though. 

i'm not really familiar with zeroconf. any ideas what i could be missing?

**Comment by benkuper** [comment]
can you post pictures ? I've usually had less problems with Chataigne than other tools to detect zeroconf services...

**Comment by joreg** [comment]
so here e.g i use [zeroconfServiceBrowser](https://www.tobias-erichsen.de/software/zeroconfservicebrowser.html) (but same for the other one linked above) where my server is seen but at the same time Chataigne doesn't see it:

![grafik](https://github.com/benkuper/Chataigne/assets/1067952/4bd7ce9d-9c57-4a37-b5cc-a50c19e3de38)

any idea how i could debug this further?

**Comment by joreg** [comment]
my bad. nobody told me i need to install [apple bonjour printer services](https://support.apple.com/kb/DL999?locale=de_DE)...
so without that some things already work, but apparently not all.. 

so now i see the service, i can select it, but then nothing happens. only when i click "Sync Data", i get an actual connection. any ideas re this?

**Comment by benkuper** [comment]
It's because the "auto detect" is only setting host and port, but in your case neither the host nor the port changed when setting them, so it didn't trigger automatically a sync. So you need to trigger manuallu Sync Data.
This could change and force a sync data when choosing the server from this menu.

**Comment by joreg** [comment]
"This could change and force a sync data when choosing the server from this menu". all for it! i thought i was playing nice by following your default...
and confirmed: if i user a port other than 5678 on my server, it works without having to press "Sync Data"

**Comment by benkuper** [comment]
both will be fixed in next beta :)

**Comment by joreg** [comment]
sorry, one more: when do you fill the list that shows in "Auto detect"? it seems to me this only happens on Chataigne startup?! if i advertise my service when chataigne is already running, it doesn't show up. and also if i unadvertise my service while chataigne is running, it is not removed from that list.

**Comment by benkuper** [comment]
The list is generated on the fly when you click it.
You can see When the services are actually detected in the logger. If it appears in the logger, then it will be shown in the menu.
And updates on that are usually quite fast, within few seconds

**Comment by joreg** [comment]
"You can see When the services are actually detected in the logger". yes perfect. if i wait for them to appear in the logger, all works as expected. so i was just clicking too fast.
