### ISSUE TITLE
How to install in CM4 with Debian 12

### ISSUE THREAD

**Issue by Lung4444** [benkuper/Chataigne#198]
When run ./Chataigne-linux-armhf-1.9.17b6.AppImage
Reply is
-bash: ./Chataigne-linux-armhf-1.9.17b6.AppImage: cannot execute: required file not found
<img width="568" alt="螢幕截圖 2023-10-14 17 11 26" src="https://github.com/benkuper/Chataigne/assets/34299729/61784e89-6692-4a04-8330-6285624fb9fd">

**Comment by benkuper** [comment]
is there way you could go a bit further on investigating this ? I don't have linux tocheck

**Comment by benkuper** [comment]
you can try to do ./[...].AppImage --appimage-extract and go to the squashfs-root/usr/bin folder that has been created, and launch it from there
you may have more informations

**Comment by Lung4444** [comment]
Hi Benkuper, 
I find the aarch64 one work for me, thanks for your help. 
  
Lung 
   
   

-----原文郵件-----

寄件人： Ben ***@***.***>
收件人： benkuper ***@***.***>
副本﹕ Lung4444 ***@***.***>; Author ***@***.***>
日期： 2023年10月14日星期六 17:49 HKT
標題﹕ Re: [benkuper/Chataigne] How to install in CM4 with Debian 12 (Issue #198)

 

  you can try to do ./[...].AppImage --appimage-extract and go to the squashfs-root/usr/bin folder that has been created, and launch it from there
you may have more informations —
