### ISSUE TITLE
Audio device samplerate not recalled properly

### ISSUE THREAD

**Issue by raffaeletani** [benkuper/Chataigne#199]
**Environment**
 - OS: Windows 11 Pro 22H2
 - Version 1.9.16

**Describe the bug**
I use the https://www.bluecataudio.com/Products/Product_Connector/ to send SMPTE timecode data to chataigne from studio one.
The DAW Session is in 48kHz, so is the audio device in chataigne.

If i save and close chataigne, the samplerate gets saved in the .noisette file ( audioDeviceRate=\"48000.0\" )
When i reopen chataigne, the samplerate gets set to 44.1kHz 

**To Reproduce**
1.  Set Samplerate to 48hKz
2.  Save
3.  Close
4.  Reopen
5.  Wonder

**Expected behavior**
The samplerate should get set to what's stored

**Comment by benkuper** [comment]
Hello, user related question are more on Discord and this is more reserved for issues related to the core code.
Thank you
