### ISSUE TITLE
routeur module save not complete on 1.3.10

### ISSUE THREAD

**Issue by prdurand** [benkuper/Chataigne#21]
hi Ben
nice new version. just found an easy to repair but annoying issue.
router modules are not saved (or maybe just read and update) correctly in 1.3.10. 
it keeps the modules in each router, with the right notes to route, but doesn't keep custom name, type, channel nor pitch/number

seen on a file created with an older version, app updated via the new update feature, bug appeared.
tried to create a new file from scratch, same problem

cheers bro

**Comment by benkuper** [comment]
thanks bro :)
will look into that very soon

**Comment by prdurand** [comment]
up: after rebooting I got back type, channel and pitch/number ... so I can use it again.
Still missing custom router modules names.

Strange behavior anyway, as it seems that I already rebooted once before.

**Comment by benkuper** [comment]
Version 1.4.4 can save custom routing value names and shows original Name
