### ISSUE TITLE
SetCurrentTime, triggers Evaluate on seek

### ISSUE THREAD

**Issue by circuitb** [benkuper/Chataigne#215]
**when playing back a non realtime sequence (pause mode +  setCurrentTime ) from an external clock (osc) the triggers are not evaluated 
The Evaluate on seek is not working here
The sequences need to be in Play state to output triggers actions

**Describe the solution you'd like**
A Dirty workaround is to trig a play action on previous frame and trig pause on the next frame 

**Describe alternatives you've considered**
Evaluate on seek option should do the trick

**Comment by EmerickH** [comment]
The actual complete name of the confusing "Evaluate on Seek" function is `evaluateOnSeekAndPlay` in code.
It only applies if you seek while the sequence is playing, for example if your sequence is playing and you click to skip a little further, all the triggers in between will be triggered.
There is no function to do what you want right now., but I've suggested one here: https://github.com/benkuper/juce_timeline/pull/6
