### ISSUE TITLE
Camera input request

### ISSUE THREAD

**Issue by MoorPoor** [benkuper/Chataigne#216]
Hei!
I recently came across chataign via VIMIX and see great use for interactive video mappings.
while working with this software combination, I'm wondering whether a USB camera would be an option as an input in order to be able to use changes in the image for triggering.

Possible functions:
- Monitor specified areas for pixel changes/brightness changes for trigger signals
- blob tracker that follows a bright point in the image and outputs coordinates for mapping to whatever
- maybe a little too much: people or object tracking

as I`m new to chataigne, I hope I didn't miss any conversation regarding this topic.
Great software, thank you so much!

**Comment by benkuper** [comment]
This would be the role of a third-party software. Integrating image processing in Chataigne would defeat the purpose of a "control-only" philosophy.
The goal is to keep Chataigne as light as possible, any simple and fast signal processing can definitely be inside, but  image / video processing and playback are out of scope. That being said, having a small tool in Processing, TouchDesigner or anything else that processes and then outputs OSC Messages would be quite easy to do for a lot of people,and then you can use the data in Chataigne.
