### ISSUE TITLE
read out PTZ Commands and FreeD Data.

### ISSUE THREAD

**Issue by Klaus-Spitzbart** [benkuper/Chataigne#217]
I want to read out PTZ Commands and FreeD Data.
To Save it, to change it and send it.

Is this possible?

**Comment by EmptyMusicBox** [comment]
Hi !! 
I'm loking fo a solution to translate Free-D to OSC

**Comment by benkuper** [comment]
You can ask on Discord and see if other people are interested in making a module for it
