### ISSUE TITLE
How to delete an item on the dashboard ?

### ISSUE THREAD

**Issue by Marmous** [benkuper/Chataigne#222]
Hi,
I can't find the way to delete items on the dashboard. Can you help me ?
Regards,
Marmous

**Comment by calebwest-SS** [comment]
For the future, the discord is the proper place for questions like this.
That being said:
Go into edit mode, click the item, and press the backspace or delete key on your keyboard.

**Comment by Marmous** [comment]
Thank you for the advices, I'll go to discord next time. Pressing backspace or delete key does not work on my side, I use Chataigne 1.9.17 on Ubuntu 22.04.4 LTS with KDE Plasma 5.24.7, can you help me ?

**Comment by benkuper** [comment]
ask on discord..
