### ISSUE TITLE
mapping send continuously

### ISSUE THREAD

**Issue by Adopo** [benkuper/Chataigne#23]
Hello Ben. I hope you are fine. I will use chataigne for a show saturday. So I tcheck the new version 1.4.1 and I have a little problem with this version.
The mapping activated send continuously data, even if the controller who manage this variable is inactif and nothing is send. It wasn't like this before. Is it normal?

**Comment by benkuper** [comment]
Hello adipose, are you using a smooth filter in your mapping ? 
Nothing changed in the code regarding the way mappings are handled but can you attach or send the file, I'll check what's going on. Also I noticed some bugs I introduced in the 1.4.1 so I'll quickly push a version 1.4.2 today

**Comment by Adopo** [comment]
Yes I use a filter. I will send you the file during the day

**Comment by Adopo** [comment]
[adopo-center-openstage update copie.noisette.txt](https://github.com/benkuper/Chataigne/files/2058754/adopo-center-openstage.update.copie.noisette.txt)

It is with this file.

**Comment by Adopo** [comment]
It’s ok ! I find a solution. I have understood the new logic. Now with the consequence true and false it’s easy to desable or enable mapping ! Cool

**Comment by benkuper** [comment]
ah i understand ! you had conditions for your mapping.
I removed the conditions, and will add conditions back as filters, so the process is simpler.
For now, creating an action to activate/deactivate a mapping is the way to go indeed.
The 1.4.2 version is out now, you can check that (mappings are better handled)
