### ISSUE TITLE
 Is there a delay in the MIDI signal input mapping keyboard module?

### ISSUE THREAD

**Issue by 517002650** [benkuper/Chataigne#233]
![7f52aea01da212efb69fb43befbca3b](https://github.com/benkuper/Chataigne/assets/83255634/b3c4c551-40fa-4d34-abc7-966ac8ae3666)
Is it my fault to input MIDI mapping to keyboard module through MIDI module with a delay of about 500 milliseconds? If it is my fault, please help me answer it? Has anyone encountered the issue of delayed output when using the keyboard module?

**Comment by benkuper** [comment]
Chataigne version, OS version. please read the pre-filled issue.

**Comment by 517002650** [comment]
> Chataigne version, OS version. please read the pre-filled issue.

I specifically downloaded the historical version, but there is a delay in the output of the keyboard module in the 1.96 latest version of the Windows version. The delay is around 500 milliseconds, and the output of the keyboard module in versions below 1.95 can be tested and used normally,

**Comment by benkuper** [comment]
do you mean 1.9.6 ? the latest versions are 1.9.17 and 1.9.18b5.
Please always try the latest versions (stable and beta) before posting

**Comment by 517002650** [comment]
In versions 1.9.6 to 1.9.17, there is a delay in the output of the keyboard module, and I am using the WINDOW10 system

**Comment by 517002650** [comment]
Version 1.95 has no delay in keyboard module output, and the delay is too large compared to the latest version

**Comment by 517002650** [comment]
The keyboard module outputs of versions 1.9.6-1.9.7-1.9.8-1.9.17 have delays

**Comment by benkuper** [comment]
did you test the beta
No delay with only keyboard output on 1.9.18b5 on my system (win 11)
please try logging midi input, consequences and keyboard output to see where it comes from

**Comment by 517002650** [comment]
I will try downloading version 1.9.18b5 and let you know

**Comment by 517002650** [comment]
There is also a delay in the output of the keyboard module in version 1.9.18b4, and the problem still persists...., I didn't see the 1.9.18b4 download connection

**Comment by 517002650** [comment]
> 您是否测试过测试版 在我的系统 （Win 11） 上 1.9.18b5 上只有键盘输出没有延迟 请尝试记录 MIDI 输入、后果和键盘输出以查看它来自哪里

Found 1.9.18b5, downloaded and tested, keyboard module output issue still persists with delay

**Comment by 517002650** [comment]
> did you test the beta No delay with only keyboard output on 1.9.18b5 on my system (win 11) please try logging midi input, consequences and keyboard output to see where it comes from
![7f52aea01da212efb69fb43befbca3b](https://github.com/benkuper/Chataigne/assets/83255634/f6365291-3320-4aa3-88f0-80e6ff9381b5)

I don't know how to test where the problem is caused, I just know that the module has a startup mapping output check box, which will cause a delay. MIDI input has a delay, and keyboard module output also has a delay. The software seems to be stuck, similar to this

**Comment by 517002650** [comment]
> did you test the beta No delay with only keyboard output on 1.9.18b5 on my system (win 11) please try logging midi input, consequences and keyboard output to see where it comes from

![44a7e35c55ef7a2a8aba302b89dc405](https://github.com/benkuper/Chataigne/assets/83255634/f022af0e-465d-4910-adff-29313fe115eb)

**Comment by benkuper** [comment]
the active button you show has nothing to do with this, this is to make the state active so the actions inside are processed.
Please enable logging in midi and keyboard module and test them in separate, minimal examples.
If you don't know, you can see the documentation and video tutorials

**Comment by 517002650** [comment]
> the active button you show has nothing to do with this, this is to make the state active so the actions inside are processed. Please enable logging in midi and keyboard module and test them in separate, minimal examples. If you don't know, you can see the documentation and video tutorials

The latest version 19.17 is very strange. When using keyboard buttons to map other keyboard buttons, there is no delay, but when using MIDI to map keyboard buttons, there is a significant delay. When using version 1.9.5, everything is normal.

**Comment by benkuper** [comment]
Latest version is 1.9.18b5, not 1.9.17
Please provide more informations, try finding the exact version where you see the change (including beta), provide minimal example files to test...
anything that can help people help you !
