### ISSUE TITLE
AB Shutter3 button 

### ISSUE THREAD

**Issue by BENJ9299** [benkuper/Chataigne#236]
Hello
I want to use a bluetooth button which is usually used for selfies.
This is recognized as a keyboard on Mac and it sends the volume up command (Keycode 115) unfortunately Chataigne does not recognize this key and it is impossible for me to reprogram it...
If there is a way to find a solution, that would be great.
THANKS

**Comment by calebwest-SS** [comment]
If you are set on using Chataigne, at this point your best bet would be using something like AutoHotkey to "repatch" this input as something Chataigne can read.

**Comment by benkuper** [comment]
You can try the latest bleeding edge, I added a keycode value in the keyboard module, it may show what you need.
Also, please mention your OS and Chataigne version when posting questions, issues like that are likely OS dependant
