### ISSUE TITLE
Deleting just about anything results in crash

### ISSUE THREAD

**Issue by jhnnslmk** [benkuper/Chataigne#237]
**Environment**
 - OS: Windows 11
 - Version 1.9.18b7

**Describe the bug**
Deleting triggers, modules, custom variables, .... results in a crash dialogue.
Also tested on fresh file.
Bug happens for Del-key as well as the red X button

![image](https://github.com/benkuper/Chataigne/assets/1488726/cd7626a0-a895-4410-81f7-2c8e27c33825)

**To Reproduce**
1. Open new project
2. Create a state in the state machine or a custom variable
3. Delete it

**Comment by benkuper** [comment]
Ok b8 should be fairly more stable, I tried to fix it everywhere I found a bug. There may be some more but they should be quite easy to fix now

**Comment by benkuper** [comment]
Please confirm that 1.9.18b8 is working again
