### ISSUE TITLE
sound card input volume as input value for action

### ISSUE THREAD

**Issue by rvdalen** [benkuper/Chataigne#238]
Hi Ben, 

as the title already suggest, it is probably a small addition as the value is already there in the interface.
i'd like to use the mic volume as input in an action to make the lighting respond to speech. it seems not available at the moment.

kind regards, 
Rik

**Comment by benkuper** [comment]
yes you can already do it, what's the problem exactly ?
you have to enable inputs in the audio hardware settings, then the Values > Volume will be updated.
Then in an action, an action, choose Sound Card > volume

**Comment by rvdalen** [comment]
tnx for the quick response, it seems to work in the windows version. my sandbox environment is mac osx where it seems missing

**Comment by benkuper** [comment]
Can you post a screenshot ? Also, it would be better to go to discord for "user" problems, the github is reserved for code related things
