### ISSUE TITLE
Variable inside of an OSC message

### ISSUE THREAD

**Issue by KyleTeal** [benkuper/Chataigne#240]
Is it possible to use custom variables inside of a string input such as a custom OSC message? For example I have a module value that is an int 1-5, and I want my osc message that is normally `/exec/1/12` to be `/exec/{variable}/12`.

**Comment by norbertrostaing** [comment]
Hello, GitHub issues are for code related issues, this kind of questions
should be asked in the discord forum. (The same question has already be
posted and answered in discord)

**Comment by benkuper** [comment]
Closing as this is not a code issue (so norbert is right, must go to discord)
