### ISSUE TITLE
MA3 Custom Commands Being Erased After Restart

### ISSUE THREAD

**Issue by Dogo69Dog** [benkuper/Chataigne#244]
**Environment**
 - OS: MacOS 13.6.7
 - Version 1.9.19

**Describe the bug**
Lets say i have a button mapped to clear in the programmer in chatagien and i restart chatagine that output would be erased. 

**To Reproduce**
1. Create slate
2. map output to custom command
3.restart chatagine
4. custom command gone

**Expected behavior**
Custom command saved

**Additional context**
Using MA3 Module on mac

**Comment by benkuper** [comment]
already posted on discord, please don't cross post and keep github issues for core code, not user issues, thanks
