### ISSUE TITLE
Cannot Execute Chataigne AppImage on RPI4

### ISSUE THREAD

**Issue by Caldanwil** [benkuper/Chataigne#251]
**Environment**
 - OS: [e.g. Windows 10, MacOS 10.14]
 - Version [e.g. 1.7.2]

Hello all!

This is my first time working with a Raspberry Pi, so pardon my lack of knowledge. I didn't have trouble installing Chataigne on my mac or windows server, so this is new for me.

I have a RPI4 with the standard OS. I downloaded both version of Chataigne from the website, made them both executable (Execute by everyone), ran sudo apt install libbluetooth-dev, but neither open. When I Execute **Chataigne-linux-armhf-1.9.19.AppImage** with Terminal it will open the terminal, but it wont accept key inputs. **Chataigne-linux-x64-1.9.19.AppImage** will open terminal, then close it down immediately.

From what I could find RPI doesn't like AppImage, but what I did above should have solved that issue.
Any help would be greatly appreciated.

**Comment by benkuper** [comment]
Hello, please use Discord for user related issue, this is reserved for core dev

**Comment by Caldanwil** [comment]
Oh, of course. Sorry!
