### ISSUE TITLE
how to send midi signal to other aplication (lumidmx)

### ISSUE THREAD

**Issue by lumidmx** [benkuper/Chataigne#252]
i have Akai mini Apc mk2
-midi in - akai mini apc    (only with this  button on akai is working)
-midi out- akai mini apc  (only with this leds on akai are change state by press button)

and i need "midi in"  -  in lumidmx  (same midi in if posible)

If i start chataigne first - midi in is take by chataigne and does not send dmx to lumidmx ...  and if i start lumidx first - chataigne does not recive midi in

I need  midi in to work toghether in chataigne and lumidmx or to send an virtual midi that is working in lumidmx

Thanks 
Filip Gabriel

**Comment by benkuper** [comment]
Hello, please ask on Discord, not here. This is for code only, not user related

**Comment by lumidmx** [comment]
can u help with an advice? ..  this is about chataighe settings 
Thanks 
Best regards

**Comment by benkuper** [comment]
Discord, as already said in the mail I sent and in previous message. please don't insist here.
