### ISSUE TITLE
Error fetching community modules

### ISSUE THREAD

**Issue by qfisch** [benkuper/Chataigne#254]
**Environment**
 - OS: Windows 10
 - Version 1.9.24

**Describe the bug**
In logs: Error fetching community modules,wrong data format
![image](https://github.com/user-attachments/assets/bbfc105d-7294-4289-881a-f500e296062e)

**To Reproduce**
Install chataigne and open it 

**Expected behavior**
community modules loaded

**Additional context**
I had it working at some point, but suddenly it did not load community modules anymore.
I tried reinstalling, no success

**Comment by niklasberlin** [comment]
there was a format error in the module list (hosted here: https://github.com/benkuper/Chataigne-community-modules) should be fixed now

**Comment by qfisch** [comment]
Hej @niklasberlin 
Thanks a lot for the quick fix. :)
Maybe adding a GithubAction routine to check the formatting might help in the future ?
Thanks for the hard work

Q.

**Comment by benkuper** [comment]
> Hej @niklasberlin 
> Thanks a lot for the quick fix. :)
> Maybe adding a GithubAction routine to check the formatting might help in the future ?
> Thanks for the hard work
> 
> Q.

Yes that would be great. Would you want to try and code it ?
