### ISSUE TITLE
Web dashboard does not seem to work

### ISSUE THREAD

**Issue by KopiasCsaba** [benkuper/Chataigne#262]
**Environment**
 - OS: Linux, W11
 - Version: 1.9.24
 
I have made a dashboard with a few trigger buttons and enabled in the project settings the webserver. 
Firefox shows white, chrome says can't load the page.

On linux it seems it is listening atleast:
```
$ netstat -lntu | grep 9999
tcp6       0      0 :::9999                 :::*                    LISTEN  
```

Tried the same file on windows (having some issue #261, so it's not conclusive), but it seems to do the same on windows as well.

**Comment by benkuper** [comment]
can you try downloading the dashboard files ?

**Comment by benkuper** [comment]
File > update dashboard files

**Comment by KopiasCsaba** [comment]
Nothing changed for me, also i didn't know I need to do that (or why):)

**Comment by KopiasCsaba** [comment]
Yeah that helped, maybe its a documentation issue then. Closing for now.
