### ISSUE TITLE
Problem value condition state

### ISSUE THREAD

**Issue by Adopo** [benkuper/Chataigne#28]
I don’t know if there is a link with crash with script but since I have crash, the condition of state don’t save there value.
For example, if I have a condition of a value state_1_1 to have to be at 4, it return to 0 when I launch the program

**Comment by benkuper** [comment]
Is this with the latest bleeding edge ?
Can you link both script and noisette files ?
Do you open your .noisette directly or first open Chataigne and then open the file from the program ?
