### ISSUE TITLE
Midi script

### ISSUE THREAD

**Issue by Adopo** [benkuper/Chataigne#31]
Hello Ben. Do you have script function to send midi in module midi like send() on module osc?

**Comment by benkuper** [comment]
Not at the moment, what are you trying to achieve ?

**Comment by Adopo** [comment]
It’s for my famous rester button I trying to simplify because of to many consequences. I create trigger with script in the different modules and rester will trig these and the script send the consequences of his own module. 
I have to communicate with mainstage in midi. That’s why.

**Comment by benkuper** [comment]
The midi module will support script events and sending midi events from scripts as well.
Also, a midi template script will be automatically filled when creating new script from midi modules.
This will be released in 1.5.2
