### ISSUE TITLE
Feature Request : switch between Note/Control Change with dropdown is heavy

### ISSUE THREAD

**Issue by prdurand** [benkuper/Chataigne#33]
When mapping values in a module routeur to a MIDI channel, the default value is Control Change. A dropdown needs 2 clics and 1 move. Mapping 60 informations to notes means 180 clic and moves :)

It could be better in one of the following way : 
- allow multiple change : select multiple lines, open one of their dropdown, change applied to all
- change defaults preferences : allow to set default to either control change OR note on OR note off
- replace dropdown with a radiobuttons form. (not the best one, but already better)

thanks !!

**Comment by benkuper** [comment]
Multiple selection is not coming soon, it's very hard to achieve good behaviors.
Next version 1.5.2 will add a Global Settings "default midi router type" which allows to choose which type is created by default when adding a midi module as output router
