### ISSUE TITLE
feature request: selectable ip in osc in

### ISSUE THREAD

**Issue by guishade** [benkuper/Chataigne#35]
ip for osc input is not selectable, only port

**Comment by benkuper** [comment]
I'm not sure I follow, OSC will bind 0.0.0.0, meaning all network interfaces.
Why would you need a specific address to bind ?

**Comment by Dogo69Dog** [comment]
> I'm not sure I follow, OSC will bind 0.0.0.0, meaning all network interfaces. Why would you need a specific address to bind ?

I am trying to connect this to ma3 (a lighting software) and Chataigne is deafulting to the ip 192.168.1.160 which is NOT what i need it to get input from. I need it to get it locally from 127.0.0.255
![Screenshot 2024-03-01 at 8 43 48 PM](https://github.com/benkuper/Chataigne/assets/143454412/3a1d39ad-cb91-44b1-ae93-69bb1fc0f2fb)

**Comment by Dogo69Dog** [comment]
@benkuper
