### ISSUE TITLE
Crash spacebar on OS X

### ISSUE THREAD

**Issue by prdurand** [benkuper/Chataigne#36]
Chataigne 1.5.2 / MacBook Pro 13" mid-2012 / Mojave OSX 10.14.1 up to date
Open chataigne -> clic on State Machine Area -> press spacebar -> crash

**Comment by benkuper** [comment]
Can't reproduce on high Sierra or windows ..

**Comment by prdurand** [comment]
https://youtu.be/Nf_Q84LBx5A

**Comment by benkuper** [comment]
Just installed Mojave Final on VMWare, can't reproduce it either..
Can you try on another Mac ? Cross testing if it comes from your system or from the OS

**Comment by prdurand** [comment]
Tests in progress... I'll update this post when done

**Comment by benkuper** [comment]
any news ?
