### ISSUE TITLE
MIDI sends damaged

### ISSUE THREAD

**Issue by prdurand** [benkuper/Chataigne#37]
Chataigne 1.5.2 / midi input APC40 / midi ouput loopmidi
MIDI module output sends note instead of channels and values instead of notes
SEND Channel 2 / note 53 / value 127
RECEIVE in external midi monitor : Channel 53 / note 127 / value 1

same test done on an old chataigne 1.3.10 on the same computer and same monitor, it works well

**Comment by benkuper** [comment]
Are you talking about all midi commands or only routed values from Module Router ?

**Comment by benkuper** [comment]
should be fixed in latest bleeding edge
