### ISSUE TITLE
Probleme avec IAC

### ISSUE THREAD

**Issue by emmanuelexbrayat** [benkuper/Chataigne#40]
Salut Ben c'est Manu (Londres)
Je viens de voir un probleme avec la derniere version qui ne se connecte plus sur le port IAC du mac. Le port est bien affiché mais les voyants OUT ne s'eclairent pas.
J'ai réinstallé la version précédente et c'est revenu.

Bise

Emmanuel

**Comment by benkuper** [comment]
Salut Manu,
Merci pour le retour !
Je suis en vacances donc pas d'ordi avant lundi, je regarderai ça en rentrant.
Peux tu privilégier le forum pour ce type de retour ? GitHub est plus réservé a la partie code.

Merci !

**Comment by emmanuelexbrayat** [comment]
pas de souci pas d’urgence pour moi l’autre version fonctionne très bien.

Pour le forum je me suis pas encore inscrit, c’est l’occasion ;)

Bonnes Vacances!

Emmanuel

**Comment by benkuper** [comment]
Je n'arrive pas à reproduire le problème avec la 1.6.2, tout fonctionne.
Peux-tu préciser le problème, et éventuellement faire une capture vidéo de l'écran ?

**Comment by emmanuelexbrayat** [comment]
Salut ben on a joué aujourd'hui et on joue demain encore du coup je remonte
pas le matos pour tester mais je peux te faire ça lundi si tu veux.

Bises

**Comment by emmanuelexbrayat** [comment]
Salut Ben.

je viens de refaire le test en revenant sur ta dernière version disponible et j’ai la meme chose.

Sur l’interface rien ne change, j-ai bien mon Device OUT vers IAC BUS 1 qui s’affiche, sur les 2 versions, c’est juste que sur la nouvelle le signal ne passe pas..
Je viens de réinstaller la version précédente et ca re-fonctionne. (fichiers et tout identique).
Je te met les captures d’écran ancienne et nouvelle version.
je te met aussi les specs de mon mac. Dis moi si tu as besoin d’autre chose. La prochaine fois je ferai le post direct sur le forum, je me suis inscrit.

Bise ;)

Emmanuel
