### ISSUE TITLE
Font size on Linux seems too large

### ISSUE THREAD

**Issue by tiagovaz** [benkuper/Chataigne#41]
Hi there! I'm willing to use your lovely software for a bunch of projects and just started playing with it. 
My first impression on a 1080p screen was that the font size (+ windows controls) is quite large, see the screenshot. Any particular reason for that? Could it be reduced a bit?
Thanks.
![Screenshot from 2019-09-10 13-01-20](https://user-images.githubusercontent.com/581203/64634640-ae716680-d3cb-11e9-92bd-8c0e244256fc.png)

**Comment by benkuper** [comment]
hey,thanks for this !
what distribution are you on ? I don't get that on my Ubuntu VM, do you have some OS settings set for the global don't size ?
right now I don't have any control over the interface and implementing it would require some time as the styling is kinda spread across a lot of classes..

**Comment by tiagovaz** [comment]
Wow that was quick! I'm using a recently installed Debian Buster over Cinnamon with default font settings. I'll try to play with other environments and will let you know if anything changes. Thanks.

**Comment by tiagovaz** [comment]
Same issue when using other window managers, like LXDE and XFCE. 
By the way, at some point I was able to change the size of a panel. Not only the panel window size, but the whole content, including the font. I have no idea how I did it, is there any sort of mouse/key combination for that? If so, problem is kind of solved.

**Comment by benkuper** [comment]
strange, I've not seen this behaviour in any setup, and the screenshot in the readme is what you should get with a 1080p screen. is Chataigne the only software doing that ?

**Comment by tiagovaz** [comment]
Hi, I've tested it in another computer in a gnome-shell environment and everything looks fine. I'll close this issue and you can re-open it if the problem appears over time for other users. For now I'd consider that's something weird with my laptop installation. Thanks and sorry for the noise.

**Comment by benkuper** [comment]
Thank you for the feedback, and I hope you find a solution (I'm interested to know the cause if you get to find it !)
No problem, noise is good :)

**Comment by tommag** [comment]
Ben has just added an option to adjust the font size under the Preferences, you can find it in the latest beta releases. 
Cheers
