### ISSUE TITLE
No network interfaces listed in artnet

### ISSUE THREAD

**Issue by xseignard** [benkuper/Chataigne#43]
Hello!

First, the soft seems nice, but I cannot see any of my network interfaces in a DMX module with artnet.

I'm running macos mojave (hackintosh), and I can see my usb c ethernet adapter and send artnet with madmapper or vezér.

Regards

**Comment by benkuper** [comment]
Thank you for the feedback, I have indeed NOT implemented interface detection on OSX or Linux yet, although you should still be able to send ArtNet using the "All" interface (you still see "All" and "Broadcast" interfaces, right ?)

**Comment by xseignard** [comment]
Yes, but it's not working. `Broadcast` fails (as seen on the logs), and `All` do nothing.

**Comment by benkuper** [comment]
Yes it might have other problems, I couldn't test this on Mac so much.
I found out a solution to list all the interfaces on OSX and linux, it will be included in the next release, but I'm not sure it will actually work better. I achieved sucessful artnet sending from Chataigne on OSX with the "All" interface but I think I remember that it was not very consistent... needs more testing and / or help from actual Mac developers :)

**Comment by benkuper** [comment]
@xseignard You can check out the bleeding edge version, downloadable on the website and see if it works better with the dedicated interfaces.

**Comment by benkuper** [comment]
@xseignard  Version 1.6.6 should implement it, can you confirm ?

**Comment by xseignard** [comment]
LGTM on 1.6.6b6

I haven't tried it yet, but at least interfaces are listed.

Thanks for your work

PS: I answered in RVID mailing list so you get the github sponsorship 👍 

![Capture d’écran 2019-10-28 à 13 29 50](https://user-images.githubusercontent.com/515603/67678523-15041100-f987-11e9-85ba-be9c46a62a06.png)

**Comment by benkuper** [comment]
Thank you for the feedback and for the support ! Closing it now
