### ISSUE TITLE
Automated build process?

### ISSUE THREAD

**Issue by mxmilkiib** [benkuper/Chataigne#45]
Specifically the Projucer part. This would allow Chataigne to be [packaged](https://wiki.archlinux.org/index.php/Creating_packages) for Arch Linux.

**Comment by benkuper** [comment]
Yes that is a good idea, though I don't really like the idea of having a lot of different versions of organicui, timeline and juce on different folders of my computer, though I see the value of being able to link a specific commit of Chataigne to a specific commit of the differents modules and versions.
One thing is to be sure not to break the CI, which can take time to do well.
Would you be able to do a pull request for this ?

**Comment by benkuper** [comment]
Also, AppImage is not working for you on Arch ?

**Comment by mxmilkb** [comment]
Once I figure out how to get Projucer to work to get things so to build Chataigne, I'll see about confirming if CI still words using submodules or if not what tweak needs doing.

For reference: https://github.com/localnet/aurci

I'd rather just get a regular Arch package working.

**Comment by benkuper** [comment]
@mxmilkb  any news on this ? :)

**Comment by mxmilkb** [comment]
I tried manually doing the Projucer project load/resave step, but I couldn't figure out how and gave up ;/

That though is beside the point of seeking to automate the build process so that there is no manual step required to be taken every time there is a new commit/release.

To that end, I did request of dvzrv if they could apply a [Projucer-resave-without-X11.patch](https://github.com/jpcima/juce-linux-patches/blob/master/juce-5.4.4-Projucer-resave-without-X11.patch) to the [JUCE package](https://www.archlinux.org/packages/community/x86_64/juce/) but I guess they have been busy (and/or maybe the patch is out-of-date now).

**Comment by tommag** [comment]
Hello !

I don't think that the Projucer is needed to build Chataigne. We don't need this step in the Travis configuration (and I don't have to do it to build on my computer either). The Makefile is generated by the Projucer when there is a new source file or configuration but it's not necessary to open the Projucer to build. 

@mxmilkiib did you want to create a Arch PKGBUILD to integrate the AppImage into a Arch package or build from source on your computer ?

**Comment by mxmilkiib** [comment]
@tommag I (and general distribution packagers) would prefer to build from source. I saw that JUCE 6 doesn't require the Projucer open/resave step, or are you meaning by another method with 5?

**Comment by tommag** [comment]
I've just checked the Chataigne README and I don't think that this open/resave step is necessary. As far as I remember I've never had to do it to compile Chataigne from source. 
If you want I can have a look at creating a PKGBUILD, I've spent some time on the Travis config for Linux so it should not be too different.

**Comment by mxmilkiib** [comment]
In the readme it says "Launch the Projucer and open Chataigne.juce. Save the jucer"

**Comment by tommag** [comment]
You're right. AFAIK this step is not necessary and should be removed from the readme.

**Comment by benkuper** [comment]
This step is not necessary if your JUCE path (and modules) is the same as the one saved, but is useful you need to resave and change the path for those files, so for people willing to compile, it will be most likely that they want to resave the Projucer and save from there but if there is a better way like just a script that can be launch instead, I can update the readme for that.

**Comment by tommag** [comment]
Yeah, I think a simple `sed` script could be used to search and replace the JUCE path instead. I will have a look, this would be easy to integrate in a Archlinux PKGBUILD file.

**Comment by tommag** [comment]
@benkuper Do you think that there is a way to integrate JUCE as a submodule into the Chataigne repo ? 

Currently, if a user wants to compile from source an older version of Chataigne, there is no way to know which JUCE commit was used when it was released. Except checking the release date and looking for the JUCE commit at this time but this sounds a bit hacky ;)

I'm trying to write the ArchLinux PKGBUILD but I'm stuck here : the correct way to do it is download the release tar.gz file from Github, get JUCE and the modules from Github then build. It's not a problem for the modules as they are in git submodules, but I can't just pull the latest JUCE and expect it to work with the older releases.

**Comment by benkuper** [comment]
JUCE as a submodule would make the working directory Chataigne 10GB+
I'm personnally working on multiple projects using JUCE and I don't plan on having 10GB per folder ! And I don't expect other people to be ok with that as well. I'm aware it's a consistency issue as update on the JUCE side are destructive on the Chataigne side and downgrading is quite complex. I actually don't really have answers for that, but integrating JUCE as a submodule is not one of them IMHO.
