### ISSUE TITLE
Can't run on linux mint

### ISSUE THREAD

**Issue by randomDam** [benkuper/Chataigne#46]
Hello, 
when i run Chataigne on linux Mint 19.2 :

~/Bureau$ ./Chataigne-linux-x64-1.6.9b3.AppImage

Chataigne: error while loading shared libraries: libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory

Maybe something missing...
Thank you!

**Comment by benkuper** [comment]
yes, something missing indeed :)
can you try installing libhid ? and if it doesn't work, with libhid-dev ?

**Comment by benkuper** [comment]
I tried to integrate the lib files in the latest 1.6.9b4 (soon out), please try and tell me if it works with it.

**Comment by randomDam** [comment]
yep, it work with :
libhidapi-dev

So : you need to install this with:
apt install libhidapi-dev

Thank you!

**Comment by benkuper** [comment]
good to hear !
my goal is for users to not have to install this lib, do you have a way to know which files I need to integrate in the AppImage in order to avoid dependencies issues with this lib ?

**Comment by mxmilkb** [comment]
```
% ./Chataigne-linux-x64-bleedingedge.AppImage
Chataigne: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```
```
% pkgfile libcurl-gnutls.so.4
community/libcurl-gnutls
multilib/lib32-libcurl-gnutls
% p libcurl-gnutls
...
```
```
% ./Chataigne-linux-x64-bleedingedge.AppImage
Chataigne: /usr/lib/libcurl-gnutls.so.4: no version information available (required by Chataigne)
/var/tmp/.mount_ChataiitLoi4/usr/bin/Chataigne: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /var/tmp/.mount_ChataiitLoi4/usr/bin/Chataigne)
```

**Comment by benkuper** [comment]
Not sure I understand this, should I integrate something in the AppImage about libcurl  ?

**Comment by mxmilkb** [comment]
Yes, if you wish Arch Linux users not to have to install the libcurl-gnutls package.

Even with that package installed there is a warning message, but the app works.

**Comment by benkuper** [comment]
would you do a pull request for it ? :)
