### ISSUE TITLE
Problem action button + wiimote

### ISSUE THREAD

**Issue by Adopo** [benkuper/Chataigne#49]
Hello Ben I hope you are fine. It's been a long time. I just put a little issue because I have seen a little bug in chataigne.

When you define a wiimote in a value condition in action, if you select + button he select - button. So there is no way to select - button.

Big up for your software. I met à song ingineer in belgium and he knew it. Lot of  people had ever eared about chataigne. It's cool !

**Comment by benkuper** [comment]
Hey BlackA, thank you for your message and feedback (and donation ;)).
Please use the forum for non-developer related questions and bugs !
This is now fixed and will be integrated in 1.6.13b4

**Comment by Adopo** [comment]
Ahah no probleme for donation. is nothing compare to your work !

Ok. Next time I will use the forum. Thank you for you reactivity !!!!
