### ISSUE TITLE
2d voronoi target vars dont control target

### ISSUE THREAD

**Issue by nimitch** [benkuper/Chataigne#51]
this is the case on all mac os builds, will test on raspberry pi and windows

**Comment by benkuper** [comment]
hello, please use the forum next time to post non-dev question thanks :)

yes that is actually normal, this is not intended to. the value of a target parameter is the target itself, not the Target's value. so the 2d voronoi (and any other variable control mode in the custom variables) will have no effect on target parameters when interpolating. what you should do then is create a mapping with a custom variable as I out, and the parameter you want to change as output. another way would be to right click on the parameter you want to control, choose "reference" as a control mode, and choose the custom variable you want it to be controlled by.
