### ISSUE TITLE
recording on a 2D track crash 1.70b29

### ISSUE THREAD

**Issue by circuitb** [benkuper/Chataigne#59]
instant crash when trying to record a 2D value (Osc input)

**Comment by benkuper** [comment]
Can you specify which version, OS and maybe provide a file ? what value are you recording from ?

**Comment by circuitb** [comment]
play then stop then crash
[rec2D_crash.zip](https://github.com/benkuper/Chataigne/files/4787354/rec2D_crash.zip)

![image](https://user-images.githubusercontent.com/1019218/84791831-6edb4900-aff3-11ea-99e0-937d3f0fa2fd.png)

**Comment by benkuper** [comment]
It seems that it happens when recording but the input parameter has not changed since start of recording. This is fixed now

**Comment by circuitb** [comment]
that was fast ;)

**Comment by benkuper** [comment]
:)
