### ISSUE TITLE
[bug] custom variable preset

### ISSUE THREAD

**Issue by siteswapjuggler** [benkuper/Chataigne#61]
**Describe the bug**
Custom variable preset does not load properly on 1.7.1

**To Reproduce**
1. create custom variables
2. create a preset
3. quit program or choose new programm then load
4. see the result : values in presets are offseted and "new [type] paremeter" box appears in presets

**Expected behavior**
Preset values should load and prompt correctly

**Environment**
 - OS: Mac Os version 1.7.1

**Additional context**
I had some module router and state machine running in the background linking those custom variable and some OSC module

**Comment by benkuper** [comment]
Hey, thank you very much,
Indeed I fixed something a bit too quickly in the latest version.. this will be fixed in 1.7.2 !

**Comment by siteswapjuggler** [comment]
Perfect, I got it working by getting back to version 1.6.12.

I've notice some other non blocking issue, I'll take time to document after we finish the current installation.

Thanks for your answer.

**Comment by benkuper** [comment]
1.7.2 is now online and fixes this.
Yes please share what you're doing, and there is also the forum and the discord if you have other questions. I actually try to keep the github dedicated to source-code related issues, and the forum for software related things. The discord is open-space for sharing, asking, proposing ideas :)
