### ISSUE TITLE
Custom Variables Preset Triggering causes instant Crash 

### ISSUE THREAD

**Issue by siteswapjuggler** [benkuper/Chataigne#63]
**Environment**
 - OS: Mac OS 10.13.6
 - Version 1.7.2 and 1.7.3b

**Describe the bug**
Triggering a Set preset on Go to preset in a sequence causes instant crash. Tired on a trigger layer and with the trigger button in the trigger inspector.

**To Reproduce**
1.  have custom variable
2. have a preset
3. trigger it from a sequence the trigger layer

**Expected behavior**
Is not expected to crash

**Additional context**
Do not happen in version 1.7.1 but only since the correction in version 1.7.2

**Comment by benkuper** [comment]
can you join your file please

**Comment by benkuper** [comment]
fixed in 1.7.3
