### ISSUE TITLE
OSCQuery implementation doesn't respect HOST_INFO OSC_PORT

### ISSUE THREAD

**Issue by alexdmiller** [benkuper/Chataigne#65]
**Environment**
 - OS: MacOS 10.15.5
 - Version: 1.7.4

**Describe the bug**
I believe Chataigne is not using the `OSC_PORT` from OSCQuery's `HOST_INFO` object. See `HOST_INFO` in the protocol [here](https://github.com/Vidvox/OSCQueryProposal#required-attributes).

**To Reproduce**
1. Add an OSCQuery module
2. In the inspector, click "Auto detect" and select an OSCQuery server

**Expected behavior**
The "Remote port" should be automatically set to the `OSC_PORT` found by navigating to `127.0.0.1:{oscquery_port}/?HOST_INFO`. Instead, "Remote port" is set to the OSCQuery port. In the spec, it says this should be the default behavior if no `OSC_PORT` is provided, but that `OSC_PORT` should be respected if provided.

**Comment by benkuper** [comment]
Thank you for the feedback, I'll check that when I get some time

**Comment by alexdmiller** [comment]
I might have time today/tomorrow to take a look myself, but I'm not sure how long it will take to get the build up and running.

Do you think you will get to it in the next couple of days? If not, I'll take a crack at it!

**Comment by benkuper** [comment]
This is now working :)
