### ISSUE TITLE
Can't copy and paste sequence automation

### ISSUE THREAD

**Issue by natarii** [benkuper/Chataigne#67]
**Environment**
 - OS: Ubuntu 18.04.5 LTS 5.9.0-050900rc1-generic #202008162130 SMP Sun Aug 16 21:35:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Version 1.7.3 or newer

**Describe the bug**
It does not seem possible to paste sequence automation events. According to the log they are copied to the clipboard, but pasting them does nothing

**To Reproduce**
1. Create a mapping in a sequence and add some points
2. Copy to clipboard
3. Attempt to paste

**Expected behavior**
The items should be pasted at the time marker

**Additional context**
Works in 1.7.2

**Comment by benkuper** [comment]
Thanks for the feedback, I'll check that

**Comment by benkuper** [comment]
This has been fixed in 1.7.5
