### ISSUE TITLE
Gamepad input not working on fresh app start

### ISSUE THREAD

**Issue by natarii** [benkuper/Chataigne#68]
**Environment**
 - OS: Ubuntu 18.04.5 LTS 5.9.0-050900rc1-generic #202008162130 SMP Sun Aug 16 21:35:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Version 1.7.4, 1.7.5b8
-  Gamepad: PlayStation 4 dualshock via USB

**Describe the bug**
Under some conditions, gamepad input is not recognized

**To Reproduce**
1. Connect gamepad to PC
2. Open Chataigne, add the gamepad module, select the device
3. Create some mappings or something to test the gamepad. Gamepad works OK
4. Save noisette file
5. Close and reopen Chataigne
6. Open noisette file
7. The correct gamepad is selected, but no data is being received from it, according to the inspector.

**Expected behavior**
Gamepad should work normally after reloading.

**Workaround**
Unplug gamepad before starting Chataigne, plug it back in only after loading the noisette file.

**Additional context**
Unfortunately I do not have any other gamepads to test. Currently unable to narrow down whether is a Linux or Dual Shock 4 related issue...

**Comment by benkuper** [comment]
Ok thanks for that, I don't know when or how I'll be able to test that but this is valuable feedback :

**Comment by benkuper** [comment]
This should have been fixed in the past updates, 1.7.5 be ok
