### ISSUE TITLE
Copy and pasting a mapping incorrectly changes some raw serial output arguments

### ISSUE THREAD

**Issue by natarii** [benkuper/Chataigne#69]
**Environment**
 - OS: Ubuntu 18.04.5 LTS 5.9.0-050900rc1-generic #202008162130 SMP Sun Aug 16 21:35:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Version 1.7.5b8

**Describe the bug**
Copy and pasting a mapping that uses a raw serial byte output causes the first argument to be forced to have "Use for mapping" set

**To Reproduce**
1. Create a mapping that uses a raw serial output. Create two or more arguments. Set the #1 argument to NOT be "use for mapping"
2. Copy and paste the mapping
3. Argument #1 incorrectly changed to have "use for mapping" set
![serial1](https://user-images.githubusercontent.com/18756729/93319274-ac5f9600-f7dd-11ea-9815-e3324dea6d90.png)
![serial2](https://user-images.githubusercontent.com/18756729/93319284-aec1f000-f7dd-11ea-8688-1072fc29cd96.png)

**Expected behavior**
All properties and arguments should be copied exactly, without modification

**Comment by benkuper** [comment]
Interesting one, thanks for this !

**Comment by benkuper** [comment]
This is fixed in the 1.8 cycle
