### ISSUE TITLE
can't save files since update to 1.7.5. 

### ISSUE THREAD

**Issue by SHAG-Lab** [benkuper/Chataigne#72]
**Environment**
 - OS: [Windows 10Pro]
 - Version [1.7.5]

**Describe the bug**
can not save files since the new Update 1.7.5.

**To Reproduce**
1.  try to save a File

**Bug report**
"output stream is null"

**Comment by benkuper** [comment]
Hello, sorry to hear that, though It seams that it's not a common problem, I've had no other feedback like that.
Can you try :
 - Saving to another directory (like the Desktop), to see if it's a write-access problem
 - Launching Chataigne as Admin
