### ISSUE TITLE
Can't Download Last Version 1.7.6

### ISSUE THREAD

**Issue by johnman51** [benkuper/Chataigne#73]
**Environment**
 - OS: ARM
 - Version [e.g. 1.7.6]

**Describe the bug**
1. Can't Download Last Version 1.7.6

**To Reproduce**
1. From the Website

**Comment by benkuper** [comment]
Hello, thanks for the info.
I've been switching over Github actions for deployment because Travis decided from one day to another to make it paying... 1.7.6 didn't make it in the compilations, but 1.7.7b1 should be available now, can you try ?

**Comment by johnman51** [comment]
Hello!
I've been installed this version an it seems OK!
But I had an issue with the keyboard Module witch can't work after reloading my session...
I always need to delete the keyboard module and create a new one to make my keystrokes detected again...

I'm running it on a Raspberry 3b+ with a classic Pi OS,
Everything is fine but this important issue for me...

Did you met this problem before?

Kind regards,
John (France).

**Comment by benkuper** [comment]
The 1.7.7b4 (will be out in few hours) will fix this keyboard problem, please confirm here when you get to use it
