### ISSUE TITLE
Korg NANOKONTROL not n device list since 1.7.5

### ISSUE THREAD

**Issue by Jorisweijdom** [benkuper/Chataigne#74]
**Environment**
OS:  Windows 10 64 Bit

**Describe the bug**
Cannot find my KORG NANOKONTROL 2 Midi controlleer in Chataigne since version 1.7.5 onwards

**To Reproduce**
1. install latest version
2. have Korg attached to PC before start of Chataigne
3. start Chataigne > add MIDI 
4. cannot find Korg under the 'Devices' list
NOTE: when deinstalling latest version and going back to version 1.7.4 it shows up in the list.

**Expected behavior**
to have the Korg appear in the devices list in the latest version

**Additional context**
I have installed the Korg driver. But have the same problem with or without this driver installed.

**Comment by benkuper** [comment]
Can you try on 1.7.6 ?

**Comment by Jorisweijdom** [comment]
Yes same problem. I noticed few days ago because I updated to the latest version.

**Comment by benkuper** [comment]
Do you have other midi controllers that you can test ?
Is it the bluetooth korg midi controller ?
