### ISSUE TITLE
Website defaults to insecure downloads via http

### ISSUE THREAD

**Issue by hamoid** [benkuper/Chataigne#75]
Hi hi :) Happy 2021!

I mentioned this like a year ago: the Chataigne website defaults to http. Because of that, most (all?) users are downloading binaries from an insecure http source, which makes it possible for a hacker to alter the binaries being downloaded. Not trivial, but still a risk. Distributing downloads via http may signal that not much thought is put into security, which may turn down some healthily paranoid potential users :-)

Possible solutions:
- Make the http website redirect to https. This is just a line or two in the server configuration.
- Distribute releases directly in GitHub.

Best wishes for the new year!

**Comment by benkuper** [comment]
Is this good now ?

**Comment by hamoid** [comment]
Hi!

Better! The downloads are now https :) You prefer not to default the site to https?

**Comment by benkuper** [comment]
This should be all good now, thanks
