### ISSUE TITLE
Send Payload in HTTP-Module 

### ISSUE THREAD

**Issue by AlphaMoonbaseBerlin** [benkuper/Chataigne#76]
**Is your feature request related to a problem? Please describe.**
So we were just playing arround with the HTTP-Module and it seems that there is not way of sending an actual payload when trying to rsend data.

**Describe the solution you'd like**
Add a payload-string-field in the template.

**Describe alternatives you've considered**
This is somewhat standart and not spomething crucial but would be nice for extendet control of other services.

**Additional context**

**Comment by benkuper** [comment]
Do you mean request body ?
This has already been asked on the Discord server, right now there is no support for request body, but feel free to add it in a PR :)
I'm focusing on other aspects right now, but this as been added to the roadmap, without any guarantee of time frame for now

**Comment by AlphaMoonbaseBerlin** [comment]
Good to know! 
It is nothing super urgent. I was more a little bit confused by it as it was possible to select POST as a request-method but not to attach a payload. 
We solved it by executing a simple CURL-Request. 

Looking forward for implementation.

**Comment by benkuper** [comment]
So when you mean payload, do you mean a file just some content, like json ?

**Comment by AlphaMoonbaseBerlin** [comment]
By Payload I mean anything in the request-body. 
But I think a simple String would totaly be enough as this can be easily formatted by the user and leaves space for own interpretation. 
Basicly having an additional text-field in the template where I can add a string that should be put in the request body. 
Some system offer trigger via HTTP-Requests and might need a JSON or even just a string in a Post-Request to know whats going on. 
For more complex stuff like uploading content and the like I would probably write a Node- or Python-App that can be triggered via chataigne.

**Comment by benkuper** [comment]
Can you give me an example of service that uses this kind of payload, just to understand what kind of data should be sent ?
And your CURL request line, so I can understand more. It's a bit confusing to me as it seems to be colliding with the POST parameters that already are in the request body

**Comment by benkuper** [comment]
@AlphaMoonbaseBerlin I have added a "Request with payload" command in the HTTP module that is already configured for "text/plain" content-type and has an extra "payload" field.
This will be available in the 1.8.0b25
