### ISSUE TITLE
Guide starting when current open project is not saved : cancel button does not work

### ISSUE THREAD

**Issue by Gazeld** [benkuper/Chataigne#78]
**Environment**
 - OS: Windows 10
 - Version 1.8.0b21

When starting a guide (e.g. "Getting started") and the current project is not saved, the cancel button in the "Closing document..." dialog box does not cancel the starting of the guide, but acts as "discard changes". Thus, the guide does launch, and the current project changes are lost.

**To Reproduce**
1. open a project
2. make some changes
3. go to Guides - Getting Started
4. on the "Closing document..." dialog box that shows, click on Cancel

**Expected behavior**
dialog box is closed and we return to the current project where we left it, with the current changes still there.

**Additional context**

**Comment by benkuper** [comment]
Indeed, this seems like a very minor bug though :) I'll check if there is an easy fix.
Anyway good to know that people are trying the guide out ! I was wondering...

**Comment by Gazeld** [comment]
Hehe. I would say it could be a probably easy entry for me to start with. I'll try to see the code.

**Comment by benkuper** [comment]
should be fixed in next release
