### ISSUE TITLE
Set dashboard elements to read-only

### ISSUE THREAD

**Issue by sebescudie** [benkuper/Chataigne#81]
**Is your feature request related to a problem? Please describe.**
I would like to display a value in a web GUI (dashboard) without allowing the user to modify it

**Describe the solution you'd like**
Have a `Read Only` toggle in the element's inspector in the dashboard

**Additional context**
Use case : I'd like to display the progress of a Sequence in a web GUI without allowing the end-user to edit it.
Version : 1.7.6

**Describe alternatives you've considered**
Creating a custom variable that hold's the Sequence's current position (via the Reference control mode), and send that to the dashboard. This way, the value is still editable but it has no effect on the timeline, and a user-defined value is instantly overridden when Sequence plays again.

**Comment by benkuper** [comment]
That's an interesting idea, I'll check that

**Comment by benkuper** [comment]
Latest version has option to set readonly on a custom variable ("real" readonly), and another to set read-only on any dashboard item ("ui only" readonly)

**Comment by sebescudie** [comment]
Thanks!
