### ISSUE TITLE
Format .noisette JSON project files to allow git versioning

### ISSUE THREAD

**Issue by maximetouroute** [benkuper/Chataigne#86]
Hello,

Currently the .noisette project files are a JSON saved in one very long line. Formatting the JSON with plenty of line breaks and tabs would make it friendlier with Git and allow better versionning (check diffs, make cautious merges...)

Pro : good for advanced teamwork 
Con : saving a big project will take a bit longer

What do you think ?

Thanks

**Comment by benkuper** [comment]
![image](https://user-images.githubusercontent.com/1291595/122130642-3fdef980-ce38-11eb-80d0-bf589e060fcc.png)

:)

**Comment by maximetouroute** [comment]
👍
