### ISSUE TITLE
ZeroconfManager::ZeroconfSearcher::run never returns

### ISSUE THREAD

**Issue by piem** [benkuper/Chataigne#89]
**Environment**
 - OS: linux
 - Version: starting 1.8.0b37 (e29aa4f26a8d12f55758911281e22dc82c0fe052)

**Description**
`ZeroconfManager::ZeroconfSearcher::run` never returns, preventing the main window to open

**To Reproduce**
start Chataigne from an AppImage or a local build. the application gets stuck before displaying the main window.

**Additional context**
turning off network connections didn't help. as a workaround, adding a return before `while (!threadShouldExit())` let the app open correctly

**Comment by benkuper** [comment]
b40 fixes threading problems, please update to the latest beta and test again

**Comment by piem** [comment]
i found the issue in current `HEAD`, so it isn't fixed for me in b40

**Comment by benkuper** [comment]
the run function is threaded so I'm not sure what's the problem, I just tested on my linux VM and it works

**Comment by benkuper** [comment]
@piem  can you give more details on your setup ( OS, etc.) and if you can find where the MessageManager thread (i.e. main thread) is blocking due to the ZeroconfSearcher thread ? I can't replicate this on Ubuntu, Mac or Windows

**Comment by underdoeg** [comment]
I have the same issue on an up to date arch linux installation.

Commenting out these two line fixes the issue:
https://github.com/benkuper/Chataigne/blob/master/Source/ChataigneEngine.cpp#L54
https://github.com/benkuper/Chataigne/blob/master/Source/ChataigneEngine.cpp#L55

**Comment by benkuper** [comment]
I could comment it out for linux as a temp fix.. unfortunately I don't have any good setup on linux to test that out. Best way would be for some linux users to debug from sources..

**Comment by underdoeg** [comment]
I only have the issue on my desktop computer and not on the laptop. But both run arch. The culprit is probably some package running in the background. But so far I have now idea which one.

**Comment by stephanbrunner** [comment]
... by the way, stopping avahi-daemon is another workaround and probably the reason why it runs on some computers.

**Comment by benkuper** [comment]
is it still a problem ?
