### ISSUE TITLE
Folder to save layouts in is not created automatically

### ISSUE THREAD

**Issue by YorVeX** [benkuper/Chataigne#90]
**Environment**
 - OS: Windows 10 Pro 64 Bit
 - Version 1.8.0

**Describe the bug**
After a fresh installation the Logger shows an error message saying that the layout couldn't be saved:
![image](https://user-images.githubusercontent.com/528974/125514643-0b63e809-dcdf-4eec-a2dd-07c5a16c9ad3.png)

**To Reproduce**
Install Chataigne 1.8.0 on Windows 10 Pro 64 Bit and run it. The error is immediately visible.

**Expected behavior**
Either the installer should create the folder upon installation or Chataigne should create it during runtime when it finds it doesn't exist, instead of showing an error message and letting the user manually do it.

**Additional context**
Creating the "layouts" folder manually in this location fixes the problem, after a restart no more error message is shown and a _lastSession.chalayout is created there.

**Comment by benkuper** [comment]
I've never seen this error occur.. It means that you don't even have the rights to create a folder from your user rights... weirs

**Comment by YorVeX** [comment]
I definitely had the permissions, creating this folder (from my user) was what fixed it after all ;-)

So you can't reproduce this error if you delete the folder and start Chataigne 1.8.0? Then that's really weird.

**Comment by benkuper** [comment]
Oh, actually I can now !
Will fix it while I can reproduce it :)

**Comment by benkuper** [comment]
Fixed ! in next release

**Comment by YorVeX** [comment]
Nice \o/
