### ISSUE TITLE
LTC timecode support

### ISSUE THREAD

**Issue by Bambi8000** [benkuper/Chataigne#91]
LTC timecode sync for timeline events. 
We have a show that is run from a LTC timecode and it would be awesome to trigger osc messages at specific times.

**Comment by benkuper** [comment]
Do you mean synch "from" a LTC signal or generate one ?

**Comment by Bambi8000** [comment]
Sync from LTC

**Comment by Bambi8000** [comment]
In the Sequence a start time would need to be specified in the 24h-space. We have LTC-code that on every song, it starts from a new hour
Song 1 01:00:00:00 forward
Song2 02:00 :00:00 forward and so on.

**Comment by Bambi8000** [comment]
Or just to have a 24h long one sequence, that would work for me too. The playhead would jump to the right position from the LTC-code

**Comment by je71175** [comment]
Adding a vote to generate LTC to the wish list :)

**Comment by benkuper** [comment]
Latest version 1.9.1b8 has LTC support :)
Enjoy
