### ISSUE TITLE
Parameters not correctly reloaded.

### ISSUE THREAD

**Issue by Shuptuu** [benkuper/Chataigne#92]
**Environment**
- OS: Windows 10 
- Version 1.8.0

**Describe the bug**
When you create a project, do some configuration, save the project, close everything, re-open Chataigne and call back your project, some settings are not correctly re-loaded. So far, I found two situations:

- Value in a triger consequence for a target type: Volume. Value saved: 1.0 - Value loaded: 0
- Links between inputs and an output with multiple arguments in a state mapping. Only the link for the first argument is correctly loaded. For the others, the other inputs are not available anymore. 

**To Reproduce**

- For the first one: create a sequence, add an audio track and a trigger track. Add some musique on the audio track. Create a trigger on the other one. Create a consequence "generic/set parameter value" and select the volume parameter for you audio track as the target. Operator "Equal". Value: 1. Save your project, close and re-open. The value is now 0.

- For the second one: create an OSC module, create a template with for example "/xyz" as parameter and 3 floats arguments x,y,z. Create a sequence, add 3 mapping tracks. Create a state, add a mapping, add 3 inputs (one for each mapping tracks value), add one output and select the template you created and set the links between the 3 input values and the 3 arguments. Save your project, close and re-open. Check the mapping: it's ok for the first argument but not for the others and if you want to correct, you can't cause the other input values are not available anymore in the list of the valid inputs... 

**Workaround found**
For the second problem (the mapping one), I found that by creating an other output in the mapping (a fake one) that you can delete just after, the problem is fixed! all the arguments retrieve their original link.

**Additional comment**
Bravo for this amazing work! Your app is really cool and helpfull!! ( even with this little bug which is anoying but not critical. It's just some extra work when you open your project!)

**Comment by benkuper** [comment]
Thank you for the feedback.
Can you join your file ?
Some informations are not complete (target Type : Volume -> which module and which command ?)

**Comment by Shuptuu** [comment]
I prepared a file with just those things. The original value for the triger is 1 but as you will see when opening the file, it's set to 0. For the mapping, you will see also that there's something going wrong and the workaround I found doesn't work on that file.
Have a good day!
[Test.zip](https://github.com/benkuper/Chataigne/files/7104559/Test.zip)

**Comment by benkuper** [comment]
Just tested, the problem with the volume parameter should already be fixed in the latest beta version.
I saw the other problem, I think I know how to fix it.
Thanks for reporting, have a great day !

**Comment by Shuptuu** [comment]
That's perfect!
Thank you very much

**Comment by benkuper** [comment]
1.8.1b10 is on the road, should be available in ~20min with the mapping fix as well
