### ISSUE TITLE
Setting range on a 3D point allow only to move the y point

### ISSUE THREAD

**Issue by ndavi** [benkuper/Chataigne#93]
**Environment**
 - OS: Windows 10
 - Version 1.8.2

**Describe the bug**
When is setting the range on a 3D point in the dashboard, it's show me a window with title : "Change point 2D params", then when I set the 3 params to be bound between 0 and 100, I cannot change the X and Z params

**To Reproduce**
1. Make a custom variable that has a 3D point
2. Set range of this 3D point
3. Try to move the x and z parameters
4. Cry

**Expected behavior**
I can move the sliders on x and z axis as same has the y axis

**Additional**
If I want all the sliders to work again, I have to nullify the range and restart chataigne

![image](https://user-images.githubusercontent.com/7792469/135655575-6b7a2883-ff73-4df2-8232-11ebe38d8036.png)

**Comment by benkuper** [comment]
The title is definitely wrong, but you may have misread the textfield names, it is MIN/MAX/MIN/MAX/MIN/MAX and not MIN/MIN/MIN/MAX/MAX/MAX

**Comment by ndavi** [comment]
Ah yes ! Thanks, sorry for the disturbance
