### ISSUE TITLE
Wiimote IR points

### ISSUE THREAD

**Issue by JeromeGsq** [benkuper/Chataigne#94]
Is it possible to have the coordinates of the IR points captured by the wiimote? 
If it is not yet the case, it is possible to contribute to add this feature ? How to do it please ?
Thank you

**Comment by benkuper** [comment]
Latest bleeding edge has it implemented please try before I push a beta (I couldn't test it myself)

**Comment by JeromeGsq** [comment]
@benkuper 
Thank you for your quick response. 
I installed the latest bleeding edge version, I connected my wiimote via my PC's bluetooth in the same way as the normal version. 
My wiimote displays one LED (the first one) after adding the wiimote module.
I can see the connection of my wiimote, the new IR menu, but nothing happens, no event or other when I press a button.

**Comment by benkuper** [comment]
Was it working before, or is it the first time you test ?

**Comment by JeromeGsq** [comment]
Yesterday it was working with the stable version. Here is a screenshot I take with this version.
![image](https://user-images.githubusercontent.com/6270529/135747288-43f873b0-8560-4261-9eca-3816b47e98bf.png)

**Comment by benkuper** [comment]
weird, I only added functions, didn't change anything..

**Comment by benkuper** [comment]
Well, I can't even connect to mine.. it's pairing ok now, but it says 1 devices paired and can't connect to it from chataigne. I'll try other tools to see if it's my OS or Chataigne doing weird things

**Comment by benkuper** [comment]
Ok I guess I understand why the wiimote is so complicated to connect, Windows's bluetooth stack is sh**t..
I managed to get it to connected a few times, and figured out what I had done wrong. You can check the bleeding edge now.

**Comment by JeromeGsq** [comment]
The 4 points are well recovered in the software! 
Thank you very much for the reactivity. 
I'm looking at how to re-create lightgun with 4 IR points around a screen and a wiimote. My project had already started using the .net library but I wanted to see how to use Chataigne directly. https://github.com/JeromeGsq/LightGunWiimote4Points/tree/main/NetInputs
Thank you for your help!
